/* Generated by Yosys 0.8 (git sha1 5706e90, gcc 6.3.1 -fPIC -Os) */

module digital_pll(reset, extclk_sel, osc, clockc, clockp, clockd, div, sel, dco, ext_trim);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  output clockc;
  output [3:0] clockd;
  output [1:0] clockp;
  input dco;
  input [4:0] div;
  input [25:0] ext_trim;
  input extclk_sel;
  wire ireset;
  wire \itrim[0] ;
  wire \itrim[10] ;
  wire \itrim[11] ;
  wire \itrim[12] ;
  wire \itrim[13] ;
  wire \itrim[14] ;
  wire \itrim[15] ;
  wire \itrim[16] ;
  wire \itrim[17] ;
  wire \itrim[18] ;
  wire \itrim[19] ;
  wire \itrim[1] ;
  wire \itrim[20] ;
  wire \itrim[21] ;
  wire \itrim[22] ;
  wire \itrim[23] ;
  wire \itrim[24] ;
  wire \itrim[25] ;
  wire \itrim[2] ;
  wire \itrim[3] ;
  wire \itrim[4] ;
  wire \itrim[5] ;
  wire \itrim[6] ;
  wire \itrim[7] ;
  wire \itrim[8] ;
  wire \itrim[9] ;
  wire \nint[0] ;
  wire \nint[1] ;
  wire \nint[2] ;
  wire \nint[3] ;
  input osc;
  wire \pll_control.clock ;
  wire \pll_control.count0[0] ;
  wire \pll_control.count0[1] ;
  wire \pll_control.count0[2] ;
  wire \pll_control.count0[3] ;
  wire \pll_control.count0[4] ;
  wire \pll_control.count1[0] ;
  wire \pll_control.count1[1] ;
  wire \pll_control.count1[2] ;
  wire \pll_control.count1[3] ;
  wire \pll_control.count1[4] ;
  wire \pll_control.oscbuf[0] ;
  wire \pll_control.oscbuf[1] ;
  wire \pll_control.oscbuf[2] ;
  wire \pll_control.prep[0] ;
  wire \pll_control.prep[1] ;
  wire \pll_control.prep[2] ;
  wire \pll_control.tint[0] ;
  wire \pll_control.tint[1] ;
  wire \pll_control.tint[2] ;
  wire \pll_control.tint[3] ;
  wire \pll_control.tint[4] ;
  wire \pll_control.tval[0] ;
  wire \pll_control.tval[1] ;
  input reset;
  wire resetb;
  wire \ringosc.c[0] ;
  wire \ringosc.c[1] ;
  wire \ringosc.dstage[0].id.d0 ;
  wire \ringosc.dstage[0].id.d1 ;
  wire \ringosc.dstage[0].id.d2 ;
  wire \ringosc.dstage[0].id.in ;
  wire \ringosc.dstage[0].id.out ;
  wire \ringosc.dstage[0].id.ts ;
  wire \ringosc.dstage[10].id.d0 ;
  wire \ringosc.dstage[10].id.d1 ;
  wire \ringosc.dstage[10].id.d2 ;
  wire \ringosc.dstage[10].id.in ;
  wire \ringosc.dstage[10].id.out ;
  wire \ringosc.dstage[10].id.ts ;
  wire \ringosc.dstage[11].id.d0 ;
  wire \ringosc.dstage[11].id.d1 ;
  wire \ringosc.dstage[11].id.d2 ;
  wire \ringosc.dstage[11].id.out ;
  wire \ringosc.dstage[11].id.ts ;
  wire \ringosc.dstage[1].id.d0 ;
  wire \ringosc.dstage[1].id.d1 ;
  wire \ringosc.dstage[1].id.d2 ;
  wire \ringosc.dstage[1].id.out ;
  wire \ringosc.dstage[1].id.ts ;
  wire \ringosc.dstage[2].id.d0 ;
  wire \ringosc.dstage[2].id.d1 ;
  wire \ringosc.dstage[2].id.d2 ;
  wire \ringosc.dstage[2].id.out ;
  wire \ringosc.dstage[2].id.ts ;
  wire \ringosc.dstage[3].id.d0 ;
  wire \ringosc.dstage[3].id.d1 ;
  wire \ringosc.dstage[3].id.d2 ;
  wire \ringosc.dstage[3].id.out ;
  wire \ringosc.dstage[3].id.ts ;
  wire \ringosc.dstage[4].id.d0 ;
  wire \ringosc.dstage[4].id.d1 ;
  wire \ringosc.dstage[4].id.d2 ;
  wire \ringosc.dstage[4].id.out ;
  wire \ringosc.dstage[4].id.ts ;
  wire \ringosc.dstage[5].id.d0 ;
  wire \ringosc.dstage[5].id.d1 ;
  wire \ringosc.dstage[5].id.d2 ;
  wire \ringosc.dstage[5].id.out ;
  wire \ringosc.dstage[5].id.ts ;
  wire \ringosc.dstage[6].id.d0 ;
  wire \ringosc.dstage[6].id.d1 ;
  wire \ringosc.dstage[6].id.d2 ;
  wire \ringosc.dstage[6].id.out ;
  wire \ringosc.dstage[6].id.ts ;
  wire \ringosc.dstage[7].id.d0 ;
  wire \ringosc.dstage[7].id.d1 ;
  wire \ringosc.dstage[7].id.d2 ;
  wire \ringosc.dstage[7].id.out ;
  wire \ringosc.dstage[7].id.ts ;
  wire \ringosc.dstage[8].id.d0 ;
  wire \ringosc.dstage[8].id.d1 ;
  wire \ringosc.dstage[8].id.d2 ;
  wire \ringosc.dstage[8].id.out ;
  wire \ringosc.dstage[8].id.ts ;
  wire \ringosc.dstage[9].id.d0 ;
  wire \ringosc.dstage[9].id.d1 ;
  wire \ringosc.dstage[9].id.d2 ;
  wire \ringosc.dstage[9].id.ts ;
  wire \ringosc.iss.ctrl0 ;
  wire \ringosc.iss.d0 ;
  wire \ringosc.iss.d1 ;
  wire \ringosc.iss.d2 ;
  wire \ringosc.iss.one ;
  input [2:0] sel;
  sky130_fd_sc_hd_inv_4 _259_ (
    .A(\pll_control.tint[3] ),
    .Y(_021_)
  );
  sky130_fd_sc_hd_inv_4 _260_ (
    .A(\pll_control.tint[2] ),
    .Y(_022_)
  );
  sky130_fd_sc_hd_inv_4 _261_ (
    .A(\pll_control.tint[4] ),
    .Y(_023_)
  );
  sky130_fd_sc_hd_inv_4 _262_ (
    .A(dco),
    .Y(_024_)
  );
  sky130_fd_sc_hd_inv_4 _263_ (
    .A(\pll_control.tint[1] ),
    .Y(_025_)
  );
  sky130_fd_sc_hd_inv_4 _264_ (
    .A(\pll_control.tint[0] ),
    .Y(_026_)
  );
  sky130_fd_sc_hd_inv_4 _265_ (
    .A(ext_trim[23]),
    .Y(_027_)
  );
  sky130_fd_sc_hd_inv_4 _266_ (
    .A(sel[0]),
    .Y(_028_)
  );
  sky130_fd_sc_hd_inv_4 _267_ (
    .A(sel[1]),
    .Y(_029_)
  );
  sky130_fd_sc_hd_inv_4 _268_ (
    .A(\pll_control.prep[0] ),
    .Y(_030_)
  );
  sky130_fd_sc_hd_inv_4 _269_ (
    .A(\pll_control.prep[1] ),
    .Y(_031_)
  );
  sky130_fd_sc_hd_inv_4 _270_ (
    .A(\pll_control.prep[2] ),
    .Y(_032_)
  );
  sky130_fd_sc_hd_inv_4 _271_ (
    .A(\pll_control.count0[1] ),
    .Y(_033_)
  );
  sky130_fd_sc_hd_inv_4 _272_ (
    .A(\pll_control.count0[0] ),
    .Y(_034_)
  );
  sky130_fd_sc_hd_inv_4 _273_ (
    .A(\pll_control.count0[3] ),
    .Y(_035_)
  );
  sky130_fd_sc_hd_inv_4 _274_ (
    .A(\pll_control.count0[2] ),
    .Y(_036_)
  );
  sky130_fd_sc_hd_inv_4 _275_ (
    .A(\pll_control.count0[4] ),
    .Y(_037_)
  );
  sky130_fd_sc_hd_inv_4 _276_ (
    .A(\pll_control.count1[0] ),
    .Y(_038_)
  );
  sky130_fd_sc_hd_inv_4 _277_ (
    .A(\pll_control.count1[1] ),
    .Y(_039_)
  );
  sky130_fd_sc_hd_inv_4 _278_ (
    .A(\pll_control.count1[2] ),
    .Y(_040_)
  );
  sky130_fd_sc_hd_inv_4 _279_ (
    .A(\pll_control.count1[3] ),
    .Y(_041_)
  );
  sky130_fd_sc_hd_inv_4 _280_ (
    .A(\pll_control.count1[4] ),
    .Y(_042_)
  );
  sky130_fd_sc_hd_inv_4 _281_ (
    .A(\pll_control.tval[0] ),
    .Y(_043_)
  );
  sky130_fd_sc_hd_inv_4 _282_ (
    .A(div[4]),
    .Y(_044_)
  );
  sky130_fd_sc_hd_inv_4 _283_ (
    .A(div[2]),
    .Y(_045_)
  );
  sky130_fd_sc_hd_inv_4 _284_ (
    .A(div[1]),
    .Y(_046_)
  );
  sky130_fd_sc_hd_inv_4 _285_ (
    .A(div[0]),
    .Y(_047_)
  );
  sky130_fd_sc_hd_inv_4 _286_ (
    .A(\pll_control.tval[1] ),
    .Y(_048_)
  );
  sky130_fd_sc_hd_or2_4 _287_ (
    .A(extclk_sel),
    .B(reset),
    .X(ireset)
  );
  sky130_fd_sc_hd_nor2_4 _288_ (
    .A(dco),
    .B(ireset),
    .Y(_020_)
  );
  sky130_fd_sc_hd_or2_4 _289_ (
    .A(\pll_control.tint[3] ),
    .B(\pll_control.tint[2] ),
    .X(_049_)
  );
  sky130_fd_sc_hd_inv_4 _290_ (
    .A(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd_and4_4 _291_ (
    .A(_025_),
    .B(_026_),
    .C(_050_),
    .D(_023_),
    .X(_051_)
  );
  sky130_fd_sc_hd_or2_4 _292_ (
    .A(dco),
    .B(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd_a21bo_4 _293_ (
    .A1(ext_trim[0]),
    .A2(dco),
    .B1N(_052_),
    .X(\itrim[0] )
  );
  sky130_fd_sc_hd_or2_4 _294_ (
    .A(_025_),
    .B(_026_),
    .X(_053_)
  );
  sky130_fd_sc_hd_inv_4 _295_ (
    .A(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd_and4_4 _296_ (
    .A(\pll_control.tint[1] ),
    .B(\pll_control.tint[0] ),
    .C(_023_),
    .D(_050_),
    .X(_055_)
  );
  sky130_fd_sc_hd_and2_4 _297_ (
    .A(_021_),
    .B(\pll_control.tint[2] ),
    .X(_056_)
  );
  sky130_fd_sc_hd_and4_4 _298_ (
    .A(_025_),
    .B(_026_),
    .C(_023_),
    .D(_056_),
    .X(_057_)
  );
  sky130_fd_sc_hd_or2_4 _299_ (
    .A(_055_),
    .B(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd_and4_4 _300_ (
    .A(_025_),
    .B(\pll_control.tint[0] ),
    .C(_023_),
    .D(_056_),
    .X(_059_)
  );
  sky130_fd_sc_hd_or2_4 _301_ (
    .A(_058_),
    .B(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd_and4_4 _302_ (
    .A(\pll_control.tint[1] ),
    .B(_026_),
    .C(_023_),
    .D(_050_),
    .X(_061_)
  );
  sky130_fd_sc_hd_and4_4 _303_ (
    .A(_025_),
    .B(\pll_control.tint[0] ),
    .C(_023_),
    .D(_050_),
    .X(_062_)
  );
  sky130_fd_sc_hd_or2_4 _304_ (
    .A(_052_),
    .B(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd_or2_4 _305_ (
    .A(_061_),
    .B(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd_or2_4 _306_ (
    .A(_060_),
    .B(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd_or2_4 _307_ (
    .A(_021_),
    .B(\pll_control.tint[2] ),
    .X(_066_)
  );
  sky130_fd_sc_hd_and4_4 _308_ (
    .A(_023_),
    .B(_054_),
    .C(\pll_control.tint[3] ),
    .D(_022_),
    .X(_067_)
  );
  sky130_fd_sc_hd_or4_4 _309_ (
    .A(_025_),
    .B(\pll_control.tint[0] ),
    .C(\pll_control.tint[4] ),
    .D(_066_),
    .X(_068_)
  );
  sky130_fd_sc_hd_inv_4 _310_ (
    .A(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd_or2_4 _311_ (
    .A(_067_),
    .B(_069_),
    .X(_070_)
  );
  sky130_fd_sc_hd_and4_4 _312_ (
    .A(\pll_control.tint[1] ),
    .B(_026_),
    .C(_023_),
    .D(_056_),
    .X(_071_)
  );
  sky130_fd_sc_hd_and2_4 _313_ (
    .A(_054_),
    .B(_056_),
    .X(_072_)
  );
  sky130_fd_sc_hd_and2_4 _314_ (
    .A(_023_),
    .B(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd_or2_4 _315_ (
    .A(_071_),
    .B(_073_),
    .X(_074_)
  );
  sky130_fd_sc_hd_or4_4 _316_ (
    .A(\pll_control.tint[1] ),
    .B(_026_),
    .C(\pll_control.tint[4] ),
    .D(_066_),
    .X(_075_)
  );
  sky130_fd_sc_hd_inv_4 _317_ (
    .A(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd_and4_4 _318_ (
    .A(_025_),
    .B(_026_),
    .C(\pll_control.tint[3] ),
    .D(_022_),
    .X(_077_)
  );
  sky130_fd_sc_hd_and2_4 _319_ (
    .A(_023_),
    .B(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd_or2_4 _320_ (
    .A(_076_),
    .B(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd_or4_4 _321_ (
    .A(_074_),
    .B(_079_),
    .C(_070_),
    .D(_065_),
    .X(_080_)
  );
  sky130_fd_sc_hd_a21bo_4 _322_ (
    .A1(dco),
    .A2(ext_trim[1]),
    .B1N(_080_),
    .X(\itrim[1] )
  );
  sky130_fd_sc_hd_or2_4 _323_ (
    .A(_055_),
    .B(_061_),
    .X(_081_)
  );
  sky130_fd_sc_hd_or2_4 _324_ (
    .A(_063_),
    .B(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd_a21o_4 _325_ (
    .A1(_023_),
    .A2(_056_),
    .B1(_082_),
    .X(_083_)
  );
  sky130_fd_sc_hd_a21bo_4 _326_ (
    .A1(dco),
    .A2(ext_trim[2]),
    .B1N(_083_),
    .X(\itrim[2] )
  );
  sky130_fd_sc_hd_a21bo_4 _327_ (
    .A1(dco),
    .A2(ext_trim[3]),
    .B1N(_082_),
    .X(\itrim[3] )
  );
  sky130_fd_sc_hd_or4_4 _328_ (
    .A(_060_),
    .B(_064_),
    .C(_074_),
    .D(_078_),
    .X(_084_)
  );
  sky130_fd_sc_hd_or2_4 _329_ (
    .A(_076_),
    .B(_084_),
    .X(_085_)
  );
  sky130_fd_sc_hd_a21bo_4 _330_ (
    .A1(dco),
    .A2(ext_trim[4]),
    .B1N(_085_),
    .X(\itrim[4] )
  );
  sky130_fd_sc_hd_or2_4 _331_ (
    .A(_061_),
    .B(_062_),
    .X(_086_)
  );
  sky130_fd_sc_hd_or2_4 _332_ (
    .A(_059_),
    .B(_071_),
    .X(_087_)
  );
  sky130_fd_sc_hd_or4_4 _333_ (
    .A(dco),
    .B(_051_),
    .C(_058_),
    .D(_087_),
    .X(_088_)
  );
  sky130_fd_sc_hd_or2_4 _334_ (
    .A(_086_),
    .B(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd_a21bo_4 _335_ (
    .A1(dco),
    .A2(ext_trim[5]),
    .B1N(_089_),
    .X(\itrim[5] )
  );
  sky130_fd_sc_hd_a21bo_4 _336_ (
    .A1(dco),
    .A2(ext_trim[6]),
    .B1N(_063_),
    .X(\itrim[6] )
  );
  sky130_fd_sc_hd_or2_4 _337_ (
    .A(_069_),
    .B(_079_),
    .X(_090_)
  );
  sky130_fd_sc_hd_or2_4 _338_ (
    .A(_083_),
    .B(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd_or2_4 _339_ (
    .A(_021_),
    .B(_022_),
    .X(_092_)
  );
  sky130_fd_sc_hd_inv_4 _340_ (
    .A(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd_and4_4 _341_ (
    .A(_025_),
    .B(_026_),
    .C(_023_),
    .D(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd_or2_4 _342_ (
    .A(_067_),
    .B(_094_),
    .X(_095_)
  );
  sky130_fd_sc_hd_or2_4 _343_ (
    .A(_091_),
    .B(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd_a21bo_4 _344_ (
    .A1(dco),
    .A2(ext_trim[7]),
    .B1N(_096_),
    .X(\itrim[7] )
  );
  sky130_fd_sc_hd_or2_4 _345_ (
    .A(_058_),
    .B(_064_),
    .X(_097_)
  );
  sky130_fd_sc_hd_a21bo_4 _346_ (
    .A1(dco),
    .A2(ext_trim[8]),
    .B1N(_097_),
    .X(\itrim[8] )
  );
  sky130_fd_sc_hd_a21bo_4 _347_ (
    .A1(dco),
    .A2(ext_trim[9]),
    .B1N(_084_),
    .X(\itrim[9] )
  );
  sky130_fd_sc_hd_a21bo_4 _348_ (
    .A1(dco),
    .A2(ext_trim[10]),
    .B1N(_064_),
    .X(\itrim[10] )
  );
  sky130_fd_sc_hd_a21bo_4 _349_ (
    .A1(dco),
    .A2(ext_trim[11]),
    .B1N(_091_),
    .X(\itrim[11] )
  );
  sky130_fd_sc_hd_a21bo_4 _350_ (
    .A1(dco),
    .A2(ext_trim[12]),
    .B1N(_065_),
    .X(\itrim[12] )
  );
  sky130_fd_sc_hd_or2_4 _351_ (
    .A(_073_),
    .B(_079_),
    .X(_098_)
  );
  sky130_fd_sc_hd_and4_4 _352_ (
    .A(_025_),
    .B(\pll_control.tint[0] ),
    .C(_023_),
    .D(_093_),
    .X(_099_)
  );
  sky130_fd_sc_hd_or2_4 _353_ (
    .A(_094_),
    .B(_099_),
    .X(_100_)
  );
  sky130_fd_sc_hd_or2_4 _354_ (
    .A(_070_),
    .B(_086_),
    .X(_101_)
  );
  sky130_fd_sc_hd_or4_4 _355_ (
    .A(_100_),
    .B(_101_),
    .C(_098_),
    .D(_088_),
    .X(_102_)
  );
  sky130_fd_sc_hd_a21bo_4 _356_ (
    .A1(dco),
    .A2(ext_trim[13]),
    .B1N(_102_),
    .X(\itrim[13] )
  );
  sky130_fd_sc_hd_or2_4 _357_ (
    .A(_097_),
    .B(_098_),
    .X(_103_)
  );
  sky130_fd_sc_hd_and4_4 _358_ (
    .A(_025_),
    .B(_026_),
    .C(\pll_control.tint[4] ),
    .D(_056_),
    .X(_104_)
  );
  sky130_fd_sc_hd_and2_4 _359_ (
    .A(\pll_control.tint[4] ),
    .B(_050_),
    .X(_105_)
  );
  sky130_fd_sc_hd_a21o_4 _360_ (
    .A1(_054_),
    .A2(_105_),
    .B1(_104_),
    .X(_106_)
  );
  sky130_fd_sc_hd_and4_4 _361_ (
    .A(_025_),
    .B(\pll_control.tint[0] ),
    .C(\pll_control.tint[4] ),
    .D(_056_),
    .X(_107_)
  );
  sky130_fd_sc_hd_and2_4 _362_ (
    .A(_053_),
    .B(_105_),
    .X(_108_)
  );
  sky130_fd_sc_hd_or2_4 _363_ (
    .A(_107_),
    .B(_108_),
    .X(_109_)
  );
  sky130_fd_sc_hd_and4_4 _364_ (
    .A(\pll_control.tint[1] ),
    .B(\pll_control.tint[0] ),
    .C(_023_),
    .D(_093_),
    .X(_110_)
  );
  sky130_fd_sc_hd_and4_4 _365_ (
    .A(\pll_control.tint[1] ),
    .B(_026_),
    .C(_023_),
    .D(_093_),
    .X(_111_)
  );
  sky130_fd_sc_hd_or2_4 _366_ (
    .A(_110_),
    .B(_111_),
    .X(_112_)
  );
  sky130_fd_sc_hd_o21a_4 _367_ (
    .A1(_072_),
    .A2(_077_),
    .B1(\pll_control.tint[4] ),
    .X(_113_)
  );
  sky130_fd_sc_hd_or4_4 _368_ (
    .A(_106_),
    .B(_109_),
    .C(_112_),
    .D(_113_),
    .X(_114_)
  );
  sky130_fd_sc_hd_or2_4 _369_ (
    .A(_070_),
    .B(_087_),
    .X(_115_)
  );
  sky130_fd_sc_hd_and4_4 _370_ (
    .A(\pll_control.tint[1] ),
    .B(_026_),
    .C(\pll_control.tint[4] ),
    .D(_056_),
    .X(_116_)
  );
  sky130_fd_sc_hd_or2_4 _371_ (
    .A(_100_),
    .B(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd_or4_4 _372_ (
    .A(_115_),
    .B(_117_),
    .C(_114_),
    .D(_103_),
    .X(_118_)
  );
  sky130_fd_sc_hd_a21bo_4 _373_ (
    .A1(dco),
    .A2(ext_trim[14]),
    .B1N(_118_),
    .X(\itrim[14] )
  );
  sky130_fd_sc_hd_or2_4 _374_ (
    .A(_100_),
    .B(_111_),
    .X(_119_)
  );
  sky130_fd_sc_hd_or2_4 _375_ (
    .A(_090_),
    .B(_119_),
    .X(_120_)
  );
  sky130_fd_sc_hd_or3_4 _376_ (
    .A(_061_),
    .B(_104_),
    .C(_110_),
    .X(_121_)
  );
  sky130_fd_sc_hd_or4_4 _377_ (
    .A(_067_),
    .B(_105_),
    .C(_074_),
    .D(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd_or4_4 _378_ (
    .A(_060_),
    .B(_063_),
    .C(_122_),
    .D(_120_),
    .X(_123_)
  );
  sky130_fd_sc_hd_a21bo_4 _379_ (
    .A1(dco),
    .A2(ext_trim[15]),
    .B1N(_123_),
    .X(\itrim[15] )
  );
  sky130_fd_sc_hd_or2_4 _380_ (
    .A(_095_),
    .B(_112_),
    .X(_124_)
  );
  sky130_fd_sc_hd_and4_4 _381_ (
    .A(_025_),
    .B(_026_),
    .C(_050_),
    .D(\pll_control.tint[4] ),
    .X(_125_)
  );
  sky130_fd_sc_hd_or4_4 _382_ (
    .A(_099_),
    .B(_125_),
    .C(_074_),
    .D(_090_),
    .X(_126_)
  );
  sky130_fd_sc_hd_or4_4 _383_ (
    .A(_060_),
    .B(_064_),
    .C(_124_),
    .D(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd_a21bo_4 _384_ (
    .A1(dco),
    .A2(ext_trim[16]),
    .B1N(_127_),
    .X(\itrim[16] )
  );
  sky130_fd_sc_hd_or4_4 _385_ (
    .A(_057_),
    .B(_116_),
    .C(_110_),
    .D(_063_),
    .X(_128_)
  );
  sky130_fd_sc_hd_or4_4 _386_ (
    .A(_081_),
    .B(_106_),
    .C(_109_),
    .D(_128_),
    .X(_129_)
  );
  sky130_fd_sc_hd_or4_4 _387_ (
    .A(_098_),
    .B(_115_),
    .C(_119_),
    .D(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd_a21bo_4 _388_ (
    .A1(dco),
    .A2(ext_trim[17]),
    .B1N(_130_),
    .X(\itrim[17] )
  );
  sky130_fd_sc_hd_or2_4 _389_ (
    .A(_100_),
    .B(_112_),
    .X(_131_)
  );
  sky130_fd_sc_hd_and2_4 _390_ (
    .A(_025_),
    .B(_105_),
    .X(_132_)
  );
  sky130_fd_sc_hd_or4_4 _391_ (
    .A(_115_),
    .B(_132_),
    .C(_131_),
    .D(_103_),
    .X(_133_)
  );
  sky130_fd_sc_hd_a21o_4 _392_ (
    .A1(\pll_control.tint[1] ),
    .A2(_105_),
    .B1(_133_),
    .X(_134_)
  );
  sky130_fd_sc_hd_a21bo_4 _393_ (
    .A1(dco),
    .A2(ext_trim[18]),
    .B1N(_134_),
    .X(\itrim[18] )
  );
  sky130_fd_sc_hd_or2_4 _394_ (
    .A(_073_),
    .B(_087_),
    .X(_135_)
  );
  sky130_fd_sc_hd_or4_4 _395_ (
    .A(_058_),
    .B(_064_),
    .C(_067_),
    .D(_135_),
    .X(_136_)
  );
  sky130_fd_sc_hd_or2_4 _396_ (
    .A(_120_),
    .B(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd_a21bo_4 _397_ (
    .A1(dco),
    .A2(ext_trim[19]),
    .B1N(_137_),
    .X(\itrim[19] )
  );
  sky130_fd_sc_hd_a32o_4 _398_ (
    .A1(\pll_control.tint[4] ),
    .A2(_056_),
    .A3(_025_),
    .B1(\pll_control.tint[1] ),
    .B2(_105_),
    .X(_138_)
  );
  sky130_fd_sc_hd_and2_4 _399_ (
    .A(_022_),
    .B(_025_),
    .X(_139_)
  );
  sky130_fd_sc_hd_o21a_4 _400_ (
    .A1(_072_),
    .A2(_139_),
    .B1(\pll_control.tint[4] ),
    .X(_140_)
  );
  sky130_fd_sc_hd_or4_4 _401_ (
    .A(_110_),
    .B(_116_),
    .C(_140_),
    .D(_138_),
    .X(_141_)
  );
  sky130_fd_sc_hd_or4_4 _402_ (
    .A(_115_),
    .B(_119_),
    .C(_141_),
    .D(_103_),
    .X(_142_)
  );
  sky130_fd_sc_hd_a21bo_4 _403_ (
    .A1(dco),
    .A2(ext_trim[20]),
    .B1N(_142_),
    .X(\itrim[20] )
  );
  sky130_fd_sc_hd_a21bo_4 _404_ (
    .A1(dco),
    .A2(ext_trim[21]),
    .B1N(_133_),
    .X(\itrim[21] )
  );
  sky130_fd_sc_hd_or4_4 _405_ (
    .A(_099_),
    .B(_132_),
    .C(_138_),
    .D(_090_),
    .X(_143_)
  );
  sky130_fd_sc_hd_or4_4 _406_ (
    .A(_124_),
    .B(_135_),
    .C(_143_),
    .D(_097_),
    .X(_144_)
  );
  sky130_fd_sc_hd_a21bo_4 _407_ (
    .A1(dco),
    .A2(ext_trim[22]),
    .B1N(_144_),
    .X(\itrim[22] )
  );
  sky130_fd_sc_hd_o22ai_4 _408_ (
    .A1(_024_),
    .A2(_027_),
    .B1(_023_),
    .B2(dco),
    .Y(\itrim[23] )
  );
  sky130_fd_sc_hd_a32o_4 _409_ (
    .A1(\pll_control.tint[4] ),
    .A2(_024_),
    .A3(\pll_control.tint[3] ),
    .B1(dco),
    .B2(ext_trim[24]),
    .X(\itrim[24] )
  );
  sky130_fd_sc_hd_or4_4 _410_ (
    .A(_090_),
    .B(_108_),
    .C(_131_),
    .D(_136_),
    .X(_145_)
  );
  sky130_fd_sc_hd_a21bo_4 _411_ (
    .A1(dco),
    .A2(ext_trim[25]),
    .B1N(_145_),
    .X(\itrim[25] )
  );
  sky130_fd_sc_hd_or2_4 _412_ (
    .A(_028_),
    .B(clockd[2]),
    .X(_146_)
  );
  sky130_fd_sc_hd_or2_4 _413_ (
    .A(sel[0]),
    .B(clockd[1]),
    .X(_147_)
  );
  sky130_fd_sc_hd_or2_4 _414_ (
    .A(_028_),
    .B(clockd[0]),
    .X(_148_)
  );
  sky130_fd_sc_hd_o21a_4 _415_ (
    .A1(sel[0]),
    .A2(\pll_control.clock ),
    .B1(_029_),
    .X(_149_)
  );
  sky130_fd_sc_hd_a32oi_4 _416_ (
    .A1(sel[1]),
    .A2(_147_),
    .A3(_146_),
    .B1(_148_),
    .B2(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd_or2_4 _417_ (
    .A(sel[2]),
    .B(_150_),
    .X(_151_)
  );
  sky130_fd_sc_hd_a21bo_4 _418_ (
    .A1(sel[2]),
    .A2(clockd[3]),
    .B1N(_151_),
    .X(clockc)
  );
  sky130_fd_sc_hd_xor2_4 _419_ (
    .A(\pll_control.oscbuf[1] ),
    .B(\pll_control.oscbuf[2] ),
    .X(_152_)
  );
  sky130_fd_sc_hd_inv_4 _420_ (
    .A(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd_or2_4 _421_ (
    .A(\pll_control.prep[0] ),
    .B(_152_),
    .X(_000_)
  );
  sky130_fd_sc_hd_o22ai_4 _422_ (
    .A1(_030_),
    .A2(_153_),
    .B1(_031_),
    .B2(_152_),
    .Y(_001_)
  );
  sky130_fd_sc_hd_o22ai_4 _423_ (
    .A1(_031_),
    .A2(_153_),
    .B1(_032_),
    .B2(_152_),
    .Y(_002_)
  );
  sky130_fd_sc_hd_and3_4 _424_ (
    .A(\pll_control.count0[1] ),
    .B(\pll_control.count0[0] ),
    .C(\pll_control.count0[2] ),
    .X(_154_)
  );
  sky130_fd_sc_hd_and2_4 _425_ (
    .A(\pll_control.count0[3] ),
    .B(_154_),
    .X(_155_)
  );
  sky130_fd_sc_hd_and2_4 _426_ (
    .A(\pll_control.count0[4] ),
    .B(_155_),
    .X(_156_)
  );
  sky130_fd_sc_hd_inv_4 _427_ (
    .A(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd_and2_4 _428_ (
    .A(\pll_control.count0[0] ),
    .B(_156_),
    .X(_158_)
  );
  sky130_fd_sc_hd_a211o_4 _429_ (
    .A1(_034_),
    .A2(_157_),
    .B1(_152_),
    .C1(_158_),
    .X(_003_)
  );
  sky130_fd_sc_hd_and3_4 _430_ (
    .A(\pll_control.count0[1] ),
    .B(\pll_control.count0[0] ),
    .C(_157_),
    .X(_159_)
  );
  sky130_fd_sc_hd_a211o_4 _431_ (
    .A1(_033_),
    .A2(_034_),
    .B1(_152_),
    .C1(_159_),
    .X(_160_)
  );
  sky130_fd_sc_hd_inv_4 _432_ (
    .A(_160_),
    .Y(_004_)
  );
  sky130_fd_sc_hd_o21a_4 _433_ (
    .A1(_033_),
    .A2(_034_),
    .B1(_036_),
    .X(_161_)
  );
  sky130_fd_sc_hd_a211o_4 _434_ (
    .A1(_154_),
    .A2(_157_),
    .B1(_152_),
    .C1(_161_),
    .X(_162_)
  );
  sky130_fd_sc_hd_inv_4 _435_ (
    .A(_162_),
    .Y(_005_)
  );
  sky130_fd_sc_hd_nor2_4 _436_ (
    .A(\pll_control.count0[3] ),
    .B(_154_),
    .Y(_163_)
  );
  sky130_fd_sc_hd_a211o_4 _437_ (
    .A1(_037_),
    .A2(_155_),
    .B1(_152_),
    .C1(_163_),
    .X(_164_)
  );
  sky130_fd_sc_hd_inv_4 _438_ (
    .A(_164_),
    .Y(_006_)
  );
  sky130_fd_sc_hd_o21a_4 _439_ (
    .A1(\pll_control.count0[4] ),
    .A2(_155_),
    .B1(_153_),
    .X(_007_)
  );
  sky130_fd_sc_hd_o22ai_4 _440_ (
    .A1(_034_),
    .A2(_153_),
    .B1(_038_),
    .B2(_152_),
    .Y(_008_)
  );
  sky130_fd_sc_hd_o22ai_4 _441_ (
    .A1(_033_),
    .A2(_153_),
    .B1(_039_),
    .B2(_152_),
    .Y(_009_)
  );
  sky130_fd_sc_hd_o22ai_4 _442_ (
    .A1(_036_),
    .A2(_153_),
    .B1(_040_),
    .B2(_152_),
    .Y(_010_)
  );
  sky130_fd_sc_hd_o22ai_4 _443_ (
    .A1(_035_),
    .A2(_153_),
    .B1(_041_),
    .B2(_152_),
    .Y(_011_)
  );
  sky130_fd_sc_hd_o22ai_4 _444_ (
    .A1(_037_),
    .A2(_153_),
    .B1(_042_),
    .B2(_152_),
    .Y(_012_)
  );
  sky130_fd_sc_hd_and2_4 _445_ (
    .A(\pll_control.count0[4] ),
    .B(\pll_control.count1[4] ),
    .X(_165_)
  );
  sky130_fd_sc_hd_a21oi_4 _446_ (
    .A1(_037_),
    .A2(_042_),
    .B1(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd_and2_4 _447_ (
    .A(_035_),
    .B(_041_),
    .X(_167_)
  );
  sky130_fd_sc_hd_and2_4 _448_ (
    .A(_036_),
    .B(_040_),
    .X(_168_)
  );
  sky130_fd_sc_hd_o22a_4 _449_ (
    .A1(_033_),
    .A2(_039_),
    .B1(\pll_control.count0[1] ),
    .B2(\pll_control.count1[1] ),
    .X(_169_)
  );
  sky130_fd_sc_hd_inv_4 _450_ (
    .A(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd_or2_4 _451_ (
    .A(_034_),
    .B(_038_),
    .X(_171_)
  );
  sky130_fd_sc_hd_inv_4 _452_ (
    .A(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd_o22a_4 _453_ (
    .A1(_033_),
    .A2(_039_),
    .B1(_170_),
    .B2(_171_),
    .X(_173_)
  );
  sky130_fd_sc_hd_o22a_4 _454_ (
    .A1(_036_),
    .A2(_040_),
    .B1(_168_),
    .B2(_173_),
    .X(_174_)
  );
  sky130_fd_sc_hd_o22ai_4 _455_ (
    .A1(_035_),
    .A2(_041_),
    .B1(_167_),
    .B2(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd_and2_4 _456_ (
    .A(_166_),
    .B(_175_),
    .X(_176_)
  );
  sky130_fd_sc_hd_or2_4 _457_ (
    .A(_166_),
    .B(_175_),
    .X(_177_)
  );
  sky130_fd_sc_hd_inv_4 _458_ (
    .A(_177_),
    .Y(_178_)
  );
  sky130_fd_sc_hd_o21a_4 _459_ (
    .A1(_176_),
    .A2(_178_),
    .B1(div[4]),
    .X(_179_)
  );
  sky130_fd_sc_hd_o21a_4 _460_ (
    .A1(\pll_control.count0[0] ),
    .A2(\pll_control.count1[0] ),
    .B1(_171_),
    .X(_180_)
  );
  sky130_fd_sc_hd_o22a_4 _461_ (
    .A1(_170_),
    .A2(_171_),
    .B1(_169_),
    .B2(_172_),
    .X(_181_)
  );
  sky130_fd_sc_hd_nor2_4 _462_ (
    .A(_046_),
    .B(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd_and2_4 _463_ (
    .A(_047_),
    .B(_180_),
    .X(_183_)
  );
  sky130_fd_sc_hd_a211o_4 _464_ (
    .A1(_046_),
    .A2(_181_),
    .B1(_183_),
    .C1(_182_),
    .X(_184_)
  );
  sky130_fd_sc_hd_inv_4 _465_ (
    .A(_184_),
    .Y(_185_)
  );
  sky130_fd_sc_hd_o21ai_4 _466_ (
    .A1(_047_),
    .A2(_180_),
    .B1(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd_a21oi_4 _467_ (
    .A1(\pll_control.count0[3] ),
    .A2(\pll_control.count1[3] ),
    .B1(_167_),
    .Y(_187_)
  );
  sky130_fd_sc_hd_xor2_4 _468_ (
    .A(_174_),
    .B(_187_),
    .X(_188_)
  );
  sky130_fd_sc_hd_a21oi_4 _469_ (
    .A1(\pll_control.count0[2] ),
    .A2(\pll_control.count1[2] ),
    .B1(_168_),
    .Y(_189_)
  );
  sky130_fd_sc_hd_xnor2_4 _470_ (
    .A(_173_),
    .B(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd_or2_4 _471_ (
    .A(_045_),
    .B(_190_),
    .X(_191_)
  );
  sky130_fd_sc_hd_a21bo_4 _472_ (
    .A1(div[3]),
    .A2(_188_),
    .B1N(_191_),
    .X(_192_)
  );
  sky130_fd_sc_hd_nor2_4 _473_ (
    .A(div[3]),
    .B(_188_),
    .Y(_193_)
  );
  sky130_fd_sc_hd_a211o_4 _474_ (
    .A1(_045_),
    .A2(_190_),
    .B1(_193_),
    .C1(_192_),
    .X(_194_)
  );
  sky130_fd_sc_hd_inv_4 _475_ (
    .A(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd_a211o_4 _476_ (
    .A1(_044_),
    .A2(_177_),
    .B1(_165_),
    .C1(_176_),
    .X(_196_)
  );
  sky130_fd_sc_hd_or4_4 _477_ (
    .A(_179_),
    .B(_186_),
    .C(_194_),
    .D(_196_),
    .X(_197_)
  );
  sky130_fd_sc_hd_or4_4 _478_ (
    .A(_030_),
    .B(_153_),
    .C(_031_),
    .D(_032_),
    .X(_198_)
  );
  sky130_fd_sc_hd_inv_4 _479_ (
    .A(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd_and2_4 _480_ (
    .A(_197_),
    .B(_199_),
    .X(_200_)
  );
  sky130_fd_sc_hd_and2_4 _481_ (
    .A(_043_),
    .B(_197_),
    .X(_201_)
  );
  sky130_fd_sc_hd_inv_4 _482_ (
    .A(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd_o22ai_4 _483_ (
    .A1(_043_),
    .A2(_200_),
    .B1(_198_),
    .B2(_202_),
    .Y(_013_)
  );
  sky130_fd_sc_hd_or2_4 _484_ (
    .A(\pll_control.tval[1] ),
    .B(_202_),
    .X(_203_)
  );
  sky130_fd_sc_hd_inv_4 _485_ (
    .A(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd_o21a_4 _486_ (
    .A1(_048_),
    .A2(_201_),
    .B1(_203_),
    .X(_205_)
  );
  sky130_fd_sc_hd_or2_4 _487_ (
    .A(_182_),
    .B(_185_),
    .X(_206_)
  );
  sky130_fd_sc_hd_o21a_4 _488_ (
    .A1(div[3]),
    .A2(_188_),
    .B1(_192_),
    .X(_207_)
  );
  sky130_fd_sc_hd_a211o_4 _489_ (
    .A1(_195_),
    .A2(_206_),
    .B1(_179_),
    .C1(_207_),
    .X(_208_)
  );
  sky130_fd_sc_hd_inv_4 _490_ (
    .A(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd_or2_4 _491_ (
    .A(_196_),
    .B(_209_),
    .X(_210_)
  );
  sky130_fd_sc_hd_inv_4 _492_ (
    .A(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd_or2_4 _493_ (
    .A(_205_),
    .B(_211_),
    .X(_212_)
  );
  sky130_fd_sc_hd_nand2_4 _494_ (
    .A(_205_),
    .B(_211_),
    .Y(_213_)
  );
  sky130_fd_sc_hd_a32o_4 _495_ (
    .A1(_199_),
    .A2(_213_),
    .A3(_212_),
    .B1(\pll_control.tval[1] ),
    .B2(_198_),
    .X(_014_)
  );
  sky130_fd_sc_hd_o22a_4 _496_ (
    .A1(_026_),
    .A2(_204_),
    .B1(\pll_control.tint[0] ),
    .B2(_203_),
    .X(_214_)
  );
  sky130_fd_sc_hd_nand2_4 _497_ (
    .A(_212_),
    .B(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd_or2_4 _498_ (
    .A(_212_),
    .B(_214_),
    .X(_216_)
  );
  sky130_fd_sc_hd_a32o_4 _499_ (
    .A1(_199_),
    .A2(_216_),
    .A3(_215_),
    .B1(\pll_control.tint[0] ),
    .B2(_198_),
    .X(_015_)
  );
  sky130_fd_sc_hd_or3_4 _500_ (
    .A(_026_),
    .B(_043_),
    .C(_048_),
    .X(_217_)
  );
  sky130_fd_sc_hd_or2_4 _501_ (
    .A(_025_),
    .B(_217_),
    .X(_218_)
  );
  sky130_fd_sc_hd_a21o_4 _502_ (
    .A1(_210_),
    .A2(_218_),
    .B1(_198_),
    .X(_219_)
  );
  sky130_fd_sc_hd_or4_4 _503_ (
    .A(\pll_control.tint[1] ),
    .B(\pll_control.tint[0] ),
    .C(\pll_control.tval[1] ),
    .D(_202_),
    .X(_220_)
  );
  sky130_fd_sc_hd_inv_4 _504_ (
    .A(_220_),
    .Y(_221_)
  );
  sky130_fd_sc_hd_or3_4 _505_ (
    .A(\pll_control.tint[0] ),
    .B(_203_),
    .C(_221_),
    .X(_222_)
  );
  sky130_fd_sc_hd_and2_4 _506_ (
    .A(_211_),
    .B(_222_),
    .X(_223_)
  );
  sky130_fd_sc_hd_and2_4 _507_ (
    .A(_211_),
    .B(_220_),
    .X(_224_)
  );
  sky130_fd_sc_hd_a211o_4 _508_ (
    .A1(_210_),
    .A2(_217_),
    .B1(_198_),
    .C1(_224_),
    .X(_225_)
  );
  sky130_fd_sc_hd_inv_4 _509_ (
    .A(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd_o22a_4 _510_ (
    .A1(_219_),
    .A2(_223_),
    .B1(\pll_control.tint[1] ),
    .B2(_226_),
    .X(_016_)
  );
  sky130_fd_sc_hd_or2_4 _511_ (
    .A(_219_),
    .B(_224_),
    .X(_227_)
  );
  sky130_fd_sc_hd_inv_4 _512_ (
    .A(_227_),
    .Y(_228_)
  );
  sky130_fd_sc_hd_o22a_4 _513_ (
    .A1(\pll_control.tint[2] ),
    .A2(_228_),
    .B1(_022_),
    .B2(_227_),
    .X(_017_)
  );
  sky130_fd_sc_hd_and2_4 _514_ (
    .A(_022_),
    .B(_221_),
    .X(_229_)
  );
  sky130_fd_sc_hd_or4_4 _515_ (
    .A(\pll_control.tint[1] ),
    .B(\pll_control.tint[0] ),
    .C(_049_),
    .D(_203_),
    .X(_230_)
  );
  sky130_fd_sc_hd_and2_4 _516_ (
    .A(_211_),
    .B(_230_),
    .X(_231_)
  );
  sky130_fd_sc_hd_o21ai_4 _517_ (
    .A1(_021_),
    .A2(_229_),
    .B1(_231_),
    .Y(_232_)
  );
  sky130_fd_sc_hd_nor3_4 _518_ (
    .A(_050_),
    .B(_093_),
    .C(_218_),
    .Y(_233_)
  );
  sky130_fd_sc_hd_a211o_4 _519_ (
    .A1(\pll_control.tint[3] ),
    .A2(_218_),
    .B1(_233_),
    .C1(_211_),
    .X(_234_)
  );
  sky130_fd_sc_hd_a32o_4 _520_ (
    .A1(_199_),
    .A2(_234_),
    .A3(_232_),
    .B1(\pll_control.tint[3] ),
    .B2(_198_),
    .X(_018_)
  );
  sky130_fd_sc_hd_a211o_4 _521_ (
    .A1(_092_),
    .A2(_210_),
    .B1(_219_),
    .C1(_231_),
    .X(_235_)
  );
  sky130_fd_sc_hd_or2_4 _522_ (
    .A(\pll_control.tint[4] ),
    .B(_235_),
    .X(_236_)
  );
  sky130_fd_sc_hd_a21bo_4 _523_ (
    .A1(\pll_control.tint[4] ),
    .A2(_235_),
    .B1N(_236_),
    .X(_019_)
  );
  sky130_fd_sc_hd_buf_4 _524_ (
    .A(_020_),
    .X(_237_)
  );
  sky130_fd_sc_hd_buf_4 _525_ (
    .A(_020_),
    .X(_238_)
  );
  sky130_fd_sc_hd_buf_4 _526_ (
    .A(_020_),
    .X(_239_)
  );
  sky130_fd_sc_hd_buf_4 _527_ (
    .A(_020_),
    .X(_240_)
  );
  sky130_fd_sc_hd_buf_4 _528_ (
    .A(_020_),
    .X(_241_)
  );
  sky130_fd_sc_hd_buf_4 _529_ (
    .A(_020_),
    .X(_242_)
  );
  sky130_fd_sc_hd_buf_4 _530_ (
    .A(_020_),
    .X(_243_)
  );
  sky130_fd_sc_hd_buf_4 _531_ (
    .A(_020_),
    .X(_244_)
  );
  sky130_fd_sc_hd_buf_4 _532_ (
    .A(_020_),
    .X(_245_)
  );
  sky130_fd_sc_hd_buf_4 _533_ (
    .A(_020_),
    .X(_246_)
  );
  sky130_fd_sc_hd_buf_4 _534_ (
    .A(_020_),
    .X(_247_)
  );
  sky130_fd_sc_hd_buf_4 _535_ (
    .A(_020_),
    .X(_248_)
  );
  sky130_fd_sc_hd_buf_4 _536_ (
    .A(_020_),
    .X(_249_)
  );
  sky130_fd_sc_hd_buf_4 _537_ (
    .A(_020_),
    .X(_250_)
  );
  sky130_fd_sc_hd_buf_4 _538_ (
    .A(_020_),
    .X(_251_)
  );
  sky130_fd_sc_hd_buf_4 _539_ (
    .A(_020_),
    .X(_252_)
  );
  sky130_fd_sc_hd_buf_4 _540_ (
    .A(_020_),
    .X(_253_)
  );
  sky130_fd_sc_hd_buf_4 _541_ (
    .A(_020_),
    .X(_254_)
  );
  sky130_fd_sc_hd_buf_4 _542_ (
    .A(_020_),
    .X(_255_)
  );
  sky130_fd_sc_hd_buf_4 _543_ (
    .A(_020_),
    .X(_256_)
  );
  sky130_fd_sc_hd_buf_4 _544_ (
    .A(_020_),
    .X(_257_)
  );
  sky130_fd_sc_hd_buf_4 _545_ (
    .A(_020_),
    .X(_258_)
  );
  sky130_fd_sc_hd_buf_2 _546_ (
    .A(\pll_control.clock ),
    .X(clockp[0])
  );
  sky130_fd_sc_hd_dfrtp_4 _547_ (
    .CLK(\pll_control.clock ),
    .D(_008_),
    .Q(\pll_control.count1[0] ),
    .RESETB(_237_)
  );
  sky130_fd_sc_hd_dfrtp_4 _548_ (
    .CLK(\pll_control.clock ),
    .D(_009_),
    .Q(\pll_control.count1[1] ),
    .RESETB(_238_)
  );
  sky130_fd_sc_hd_dfrtp_4 _549_ (
    .CLK(\pll_control.clock ),
    .D(_010_),
    .Q(\pll_control.count1[2] ),
    .RESETB(_239_)
  );
  sky130_fd_sc_hd_dfrtp_4 _550_ (
    .CLK(\pll_control.clock ),
    .D(_011_),
    .Q(\pll_control.count1[3] ),
    .RESETB(_240_)
  );
  sky130_fd_sc_hd_dfrtp_4 _551_ (
    .CLK(\pll_control.clock ),
    .D(_012_),
    .Q(\pll_control.count1[4] ),
    .RESETB(_241_)
  );
  sky130_fd_sc_hd_dfrtp_4 _552_ (
    .CLK(\pll_control.clock ),
    .D(_013_),
    .Q(\pll_control.tval[0] ),
    .RESETB(_242_)
  );
  sky130_fd_sc_hd_dfrtp_4 _553_ (
    .CLK(\pll_control.clock ),
    .D(_014_),
    .Q(\pll_control.tval[1] ),
    .RESETB(_243_)
  );
  sky130_fd_sc_hd_dfrtp_4 _554_ (
    .CLK(\pll_control.clock ),
    .D(_015_),
    .Q(\pll_control.tint[0] ),
    .RESETB(_244_)
  );
  sky130_fd_sc_hd_dfrtp_4 _555_ (
    .CLK(\pll_control.clock ),
    .D(_016_),
    .Q(\pll_control.tint[1] ),
    .RESETB(_245_)
  );
  sky130_fd_sc_hd_dfrtp_4 _556_ (
    .CLK(\pll_control.clock ),
    .D(_017_),
    .Q(\pll_control.tint[2] ),
    .RESETB(_246_)
  );
  sky130_fd_sc_hd_dfrtp_4 _557_ (
    .CLK(\pll_control.clock ),
    .D(_018_),
    .Q(\pll_control.tint[3] ),
    .RESETB(_247_)
  );
  sky130_fd_sc_hd_dfrtp_4 _558_ (
    .CLK(\pll_control.clock ),
    .D(_019_),
    .Q(\pll_control.tint[4] ),
    .RESETB(_248_)
  );
  sky130_fd_sc_hd_dfrtp_4 _559_ (
    .CLK(\pll_control.clock ),
    .D(_003_),
    .Q(\pll_control.count0[0] ),
    .RESETB(_249_)
  );
  sky130_fd_sc_hd_dfrtp_4 _560_ (
    .CLK(\pll_control.clock ),
    .D(_004_),
    .Q(\pll_control.count0[1] ),
    .RESETB(_250_)
  );
  sky130_fd_sc_hd_dfrtp_4 _561_ (
    .CLK(\pll_control.clock ),
    .D(_005_),
    .Q(\pll_control.count0[2] ),
    .RESETB(_251_)
  );
  sky130_fd_sc_hd_dfrtp_4 _562_ (
    .CLK(\pll_control.clock ),
    .D(_006_),
    .Q(\pll_control.count0[3] ),
    .RESETB(_252_)
  );
  sky130_fd_sc_hd_dfrtp_4 _563_ (
    .CLK(\pll_control.clock ),
    .D(_007_),
    .Q(\pll_control.count0[4] ),
    .RESETB(_253_)
  );
  sky130_fd_sc_hd_dfrtp_4 _564_ (
    .CLK(\pll_control.clock ),
    .D(_000_),
    .Q(\pll_control.prep[0] ),
    .RESETB(_254_)
  );
  sky130_fd_sc_hd_dfrtp_4 _565_ (
    .CLK(\pll_control.clock ),
    .D(_001_),
    .Q(\pll_control.prep[1] ),
    .RESETB(_255_)
  );
  sky130_fd_sc_hd_dfrtp_4 _566_ (
    .CLK(\pll_control.clock ),
    .D(_002_),
    .Q(\pll_control.prep[2] ),
    .RESETB(_256_)
  );
  sky130_fd_sc_hd_dfrtp_4 _567_ (
    .CLK(\pll_control.clock ),
    .D(osc),
    .Q(\pll_control.oscbuf[0] ),
    .RESETB(_257_)
  );
  sky130_fd_sc_hd_dfrtp_4 _568_ (
    .CLK(\pll_control.clock ),
    .D(\pll_control.oscbuf[0] ),
    .Q(\pll_control.oscbuf[1] ),
    .RESETB(_258_)
  );
  sky130_fd_sc_hd_dfrtp_4 _569_ (
    .CLK(\pll_control.clock ),
    .D(\pll_control.oscbuf[1] ),
    .Q(\pll_control.oscbuf[2] ),
    .RESETB(_020_)
  );
  sky130_fd_sc_hd_dfrbp_1 idiv16 (
    .CLK(clockd[2]),
    .D(clockd[3]),
    .Q(\nint[3] ),
    .QN(clockd[3]),
    .RESETB(resetb)
  );
  sky130_fd_sc_hd_dfrbp_1 idiv2 (
    .CLK(clockp[1]),
    .D(clockd[0]),
    .Q(\nint[0] ),
    .QN(clockd[0]),
    .RESETB(resetb)
  );
  sky130_fd_sc_hd_dfrbp_1 idiv4 (
    .CLK(clockd[0]),
    .D(clockd[1]),
    .Q(\nint[1] ),
    .QN(clockd[1]),
    .RESETB(resetb)
  );
  sky130_fd_sc_hd_dfrbp_1 idiv8 (
    .CLK(clockd[1]),
    .D(clockd[2]),
    .Q(\nint[2] ),
    .QN(clockd[2]),
    .RESETB(resetb)
  );
  sky130_fd_sc_hd_inv_4 irb (
    .A(reset),
    .Y(resetb)
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[0].id.delaybuf0  (
    .A(\ringosc.dstage[0].id.in ),
    .X(\ringosc.dstage[0].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[0].id.delaybuf1  (
    .A(\ringosc.dstage[0].id.ts ),
    .X(\ringosc.dstage[0].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[0].id.delayen0  (
    .A(\ringosc.dstage[0].id.d2 ),
    .TE(\itrim[0] ),
    .Z(\ringosc.dstage[0].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[0].id.delayen1  (
    .A(\ringosc.dstage[0].id.d0 ),
    .TE(\itrim[13] ),
    .Z(\ringosc.dstage[0].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[0].id.delayenb0  (
    .A(\ringosc.dstage[0].id.ts ),
    .TEB(\itrim[0] ),
    .Z(\ringosc.dstage[0].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[0].id.delayenb1  (
    .A(\ringosc.dstage[0].id.ts ),
    .TEB(\itrim[13] ),
    .Z(\ringosc.dstage[0].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[0].id.delayint0  (
    .A(\ringosc.dstage[0].id.d1 ),
    .Y(\ringosc.dstage[0].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[10].id.delaybuf0  (
    .A(\ringosc.dstage[10].id.in ),
    .X(\ringosc.dstage[10].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[10].id.delaybuf1  (
    .A(\ringosc.dstage[10].id.ts ),
    .X(\ringosc.dstage[10].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[10].id.delayen0  (
    .A(\ringosc.dstage[10].id.d2 ),
    .TE(\itrim[10] ),
    .Z(\ringosc.dstage[10].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[10].id.delayen1  (
    .A(\ringosc.dstage[10].id.d0 ),
    .TE(\itrim[23] ),
    .Z(\ringosc.dstage[10].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[10].id.delayenb0  (
    .A(\ringosc.dstage[10].id.ts ),
    .TEB(\itrim[10] ),
    .Z(\ringosc.dstage[10].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[10].id.delayenb1  (
    .A(\ringosc.dstage[10].id.ts ),
    .TEB(\itrim[23] ),
    .Z(\ringosc.dstage[10].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[10].id.delayint0  (
    .A(\ringosc.dstage[10].id.d1 ),
    .Y(\ringosc.dstage[10].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[11].id.delaybuf0  (
    .A(\ringosc.dstage[10].id.out ),
    .X(\ringosc.dstage[11].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[11].id.delaybuf1  (
    .A(\ringosc.dstage[11].id.ts ),
    .X(\ringosc.dstage[11].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[11].id.delayen0  (
    .A(\ringosc.dstage[11].id.d2 ),
    .TE(\itrim[11] ),
    .Z(\ringosc.dstage[11].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[11].id.delayen1  (
    .A(\ringosc.dstage[11].id.d0 ),
    .TE(\itrim[24] ),
    .Z(\ringosc.dstage[11].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[11].id.delayenb0  (
    .A(\ringosc.dstage[11].id.ts ),
    .TEB(\itrim[11] ),
    .Z(\ringosc.dstage[11].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[11].id.delayenb1  (
    .A(\ringosc.dstage[11].id.ts ),
    .TEB(\itrim[24] ),
    .Z(\ringosc.dstage[11].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[11].id.delayint0  (
    .A(\ringosc.dstage[11].id.d1 ),
    .Y(\ringosc.dstage[11].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[1].id.delaybuf0  (
    .A(\ringosc.dstage[0].id.out ),
    .X(\ringosc.dstage[1].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[1].id.delaybuf1  (
    .A(\ringosc.dstage[1].id.ts ),
    .X(\ringosc.dstage[1].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[1].id.delayen0  (
    .A(\ringosc.dstage[1].id.d2 ),
    .TE(\itrim[1] ),
    .Z(\ringosc.dstage[1].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[1].id.delayen1  (
    .A(\ringosc.dstage[1].id.d0 ),
    .TE(\itrim[14] ),
    .Z(\ringosc.dstage[1].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[1].id.delayenb0  (
    .A(\ringosc.dstage[1].id.ts ),
    .TEB(\itrim[1] ),
    .Z(\ringosc.dstage[1].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[1].id.delayenb1  (
    .A(\ringosc.dstage[1].id.ts ),
    .TEB(\itrim[14] ),
    .Z(\ringosc.dstage[1].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[1].id.delayint0  (
    .A(\ringosc.dstage[1].id.d1 ),
    .Y(\ringosc.dstage[1].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[2].id.delaybuf0  (
    .A(\ringosc.dstage[1].id.out ),
    .X(\ringosc.dstage[2].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[2].id.delaybuf1  (
    .A(\ringosc.dstage[2].id.ts ),
    .X(\ringosc.dstage[2].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[2].id.delayen0  (
    .A(\ringosc.dstage[2].id.d2 ),
    .TE(\itrim[2] ),
    .Z(\ringosc.dstage[2].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[2].id.delayen1  (
    .A(\ringosc.dstage[2].id.d0 ),
    .TE(\itrim[15] ),
    .Z(\ringosc.dstage[2].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[2].id.delayenb0  (
    .A(\ringosc.dstage[2].id.ts ),
    .TEB(\itrim[2] ),
    .Z(\ringosc.dstage[2].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[2].id.delayenb1  (
    .A(\ringosc.dstage[2].id.ts ),
    .TEB(\itrim[15] ),
    .Z(\ringosc.dstage[2].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[2].id.delayint0  (
    .A(\ringosc.dstage[2].id.d1 ),
    .Y(\ringosc.dstage[2].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[3].id.delaybuf0  (
    .A(\ringosc.dstage[2].id.out ),
    .X(\ringosc.dstage[3].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[3].id.delaybuf1  (
    .A(\ringosc.dstage[3].id.ts ),
    .X(\ringosc.dstage[3].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[3].id.delayen0  (
    .A(\ringosc.dstage[3].id.d2 ),
    .TE(\itrim[3] ),
    .Z(\ringosc.dstage[3].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[3].id.delayen1  (
    .A(\ringosc.dstage[3].id.d0 ),
    .TE(\itrim[16] ),
    .Z(\ringosc.dstage[3].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[3].id.delayenb0  (
    .A(\ringosc.dstage[3].id.ts ),
    .TEB(\itrim[3] ),
    .Z(\ringosc.dstage[3].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[3].id.delayenb1  (
    .A(\ringosc.dstage[3].id.ts ),
    .TEB(\itrim[16] ),
    .Z(\ringosc.dstage[3].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[3].id.delayint0  (
    .A(\ringosc.dstage[3].id.d1 ),
    .Y(\ringosc.dstage[3].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[4].id.delaybuf0  (
    .A(\ringosc.dstage[3].id.out ),
    .X(\ringosc.dstage[4].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[4].id.delaybuf1  (
    .A(\ringosc.dstage[4].id.ts ),
    .X(\ringosc.dstage[4].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[4].id.delayen0  (
    .A(\ringosc.dstage[4].id.d2 ),
    .TE(\itrim[4] ),
    .Z(\ringosc.dstage[4].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[4].id.delayen1  (
    .A(\ringosc.dstage[4].id.d0 ),
    .TE(\itrim[17] ),
    .Z(\ringosc.dstage[4].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[4].id.delayenb0  (
    .A(\ringosc.dstage[4].id.ts ),
    .TEB(\itrim[4] ),
    .Z(\ringosc.dstage[4].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[4].id.delayenb1  (
    .A(\ringosc.dstage[4].id.ts ),
    .TEB(\itrim[17] ),
    .Z(\ringosc.dstage[4].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[4].id.delayint0  (
    .A(\ringosc.dstage[4].id.d1 ),
    .Y(\ringosc.dstage[4].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[5].id.delaybuf0  (
    .A(\ringosc.dstage[4].id.out ),
    .X(\ringosc.dstage[5].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[5].id.delaybuf1  (
    .A(\ringosc.dstage[5].id.ts ),
    .X(\ringosc.dstage[5].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[5].id.delayen0  (
    .A(\ringosc.dstage[5].id.d2 ),
    .TE(\itrim[5] ),
    .Z(\ringosc.dstage[5].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[5].id.delayen1  (
    .A(\ringosc.dstage[5].id.d0 ),
    .TE(\itrim[18] ),
    .Z(\ringosc.dstage[5].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[5].id.delayenb0  (
    .A(\ringosc.dstage[5].id.ts ),
    .TEB(\itrim[5] ),
    .Z(\ringosc.dstage[5].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[5].id.delayenb1  (
    .A(\ringosc.dstage[5].id.ts ),
    .TEB(\itrim[18] ),
    .Z(\ringosc.dstage[5].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[5].id.delayint0  (
    .A(\ringosc.dstage[5].id.d1 ),
    .Y(\ringosc.dstage[5].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[6].id.delaybuf0  (
    .A(\ringosc.dstage[5].id.out ),
    .X(\ringosc.dstage[6].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[6].id.delaybuf1  (
    .A(\ringosc.dstage[6].id.ts ),
    .X(\ringosc.dstage[6].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[6].id.delayen0  (
    .A(\ringosc.dstage[6].id.d2 ),
    .TE(\itrim[6] ),
    .Z(\ringosc.dstage[6].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[6].id.delayen1  (
    .A(\ringosc.dstage[6].id.d0 ),
    .TE(\itrim[19] ),
    .Z(\ringosc.dstage[6].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[6].id.delayenb0  (
    .A(\ringosc.dstage[6].id.ts ),
    .TEB(\itrim[6] ),
    .Z(\ringosc.dstage[6].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[6].id.delayenb1  (
    .A(\ringosc.dstage[6].id.ts ),
    .TEB(\itrim[19] ),
    .Z(\ringosc.dstage[6].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[6].id.delayint0  (
    .A(\ringosc.dstage[6].id.d1 ),
    .Y(\ringosc.dstage[6].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[7].id.delaybuf0  (
    .A(\ringosc.dstage[6].id.out ),
    .X(\ringosc.dstage[7].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[7].id.delaybuf1  (
    .A(\ringosc.dstage[7].id.ts ),
    .X(\ringosc.dstage[7].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[7].id.delayen0  (
    .A(\ringosc.dstage[7].id.d2 ),
    .TE(\itrim[7] ),
    .Z(\ringosc.dstage[7].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[7].id.delayen1  (
    .A(\ringosc.dstage[7].id.d0 ),
    .TE(\itrim[20] ),
    .Z(\ringosc.dstage[7].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[7].id.delayenb0  (
    .A(\ringosc.dstage[7].id.ts ),
    .TEB(\itrim[7] ),
    .Z(\ringosc.dstage[7].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[7].id.delayenb1  (
    .A(\ringosc.dstage[7].id.ts ),
    .TEB(\itrim[20] ),
    .Z(\ringosc.dstage[7].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[7].id.delayint0  (
    .A(\ringosc.dstage[7].id.d1 ),
    .Y(\ringosc.dstage[7].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[8].id.delaybuf0  (
    .A(\ringosc.dstage[7].id.out ),
    .X(\ringosc.dstage[8].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[8].id.delaybuf1  (
    .A(\ringosc.dstage[8].id.ts ),
    .X(\ringosc.dstage[8].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[8].id.delayen0  (
    .A(\ringosc.dstage[8].id.d2 ),
    .TE(\itrim[8] ),
    .Z(\ringosc.dstage[8].id.out )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[8].id.delayen1  (
    .A(\ringosc.dstage[8].id.d0 ),
    .TE(\itrim[21] ),
    .Z(\ringosc.dstage[8].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[8].id.delayenb0  (
    .A(\ringosc.dstage[8].id.ts ),
    .TEB(\itrim[8] ),
    .Z(\ringosc.dstage[8].id.out )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[8].id.delayenb1  (
    .A(\ringosc.dstage[8].id.ts ),
    .TEB(\itrim[21] ),
    .Z(\ringosc.dstage[8].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[8].id.delayint0  (
    .A(\ringosc.dstage[8].id.d1 ),
    .Y(\ringosc.dstage[8].id.d2 )
  );
  sky130_fd_sc_hd_clkbuf_2 \ringosc.dstage[9].id.delaybuf0  (
    .A(\ringosc.dstage[8].id.out ),
    .X(\ringosc.dstage[9].id.ts )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.dstage[9].id.delaybuf1  (
    .A(\ringosc.dstage[9].id.ts ),
    .X(\ringosc.dstage[9].id.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[9].id.delayen0  (
    .A(\ringosc.dstage[9].id.d2 ),
    .TE(\itrim[9] ),
    .Z(\ringosc.dstage[10].id.in )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.dstage[9].id.delayen1  (
    .A(\ringosc.dstage[9].id.d0 ),
    .TE(\itrim[22] ),
    .Z(\ringosc.dstage[9].id.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.dstage[9].id.delayenb0  (
    .A(\ringosc.dstage[9].id.ts ),
    .TEB(\itrim[9] ),
    .Z(\ringosc.dstage[10].id.in )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.dstage[9].id.delayenb1  (
    .A(\ringosc.dstage[9].id.ts ),
    .TEB(\itrim[22] ),
    .Z(\ringosc.dstage[9].id.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.dstage[9].id.delayint0  (
    .A(\ringosc.dstage[9].id.d1 ),
    .Y(\ringosc.dstage[9].id.d2 )
  );
  sky130_fd_sc_hd_clkinv_2 \ringosc.ibufp00  (
    .A(\ringosc.dstage[0].id.in ),
    .Y(\ringosc.c[0] )
  );
  sky130_fd_sc_hd_clkinv_8 \ringosc.ibufp01  (
    .A(\ringosc.c[0] ),
    .Y(\pll_control.clock )
  );
  sky130_fd_sc_hd_clkinv_2 \ringosc.ibufp10  (
    .A(\ringosc.dstage[5].id.out ),
    .Y(\ringosc.c[1] )
  );
  sky130_fd_sc_hd_clkinv_8 \ringosc.ibufp11  (
    .A(\ringosc.c[1] ),
    .Y(clockp[1])
  );
  sky130_fd_sc_hd_conb_1 \ringosc.iss.const1  (
    .HI(\ringosc.iss.one ),
    .LO()
  );
  sky130_fd_sc_hd_or2_2 \ringosc.iss.ctrlen0  (
    .A(ireset),
    .B(\itrim[12] ),
    .X(\ringosc.iss.ctrl0 )
  );
  sky130_fd_sc_hd_clkbuf_1 \ringosc.iss.delaybuf0  (
    .A(\ringosc.dstage[11].id.out ),
    .X(\ringosc.iss.d0 )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.iss.delayen0  (
    .A(\ringosc.iss.d2 ),
    .TE(\itrim[12] ),
    .Z(\ringosc.dstage[0].id.in )
  );
  sky130_fd_sc_hd_einvp_2 \ringosc.iss.delayen1  (
    .A(\ringosc.iss.d0 ),
    .TE(\itrim[25] ),
    .Z(\ringosc.iss.d1 )
  );
  sky130_fd_sc_hd_einvn_8 \ringosc.iss.delayenb0  (
    .A(\ringosc.dstage[11].id.out ),
    .TEB(\ringosc.iss.ctrl0 ),
    .Z(\ringosc.dstage[0].id.in )
  );
  sky130_fd_sc_hd_einvn_4 \ringosc.iss.delayenb1  (
    .A(\ringosc.dstage[11].id.out ),
    .TEB(\itrim[25] ),
    .Z(\ringosc.iss.d1 )
  );
  sky130_fd_sc_hd_clkinv_1 \ringosc.iss.delayint0  (
    .A(\ringosc.iss.d1 ),
    .Y(\ringosc.iss.d2 )
  );
  sky130_fd_sc_hd_einvp_1 \ringosc.iss.reseten0  (
    .A(\ringosc.iss.one ),
    .TE(ireset),
    .Z(\ringosc.dstage[0].id.in )
  );
endmodule
