
/* Generated by Yosys 0.8 (git sha1 5706e90, gcc 6.3.1 -fPIC -Os) */

module striVe_spi(RSTB, SCK, SDI, CSB, SDO, sdo_enb, xtal_ena, reg_ena, pll_dco_ena, pll_div, pll_sel, pll_trim, pll_bypass, irq, reset, RST, trap, mfgr_id, prod_id, mask_rev_in, mask_rev);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  input CSB;
  output RST;
  input RSTB;
  input SCK;
  input SDI;
  output SDO;
  wire \U1.addr[0] ;
  wire \U1.addr[1] ;
  wire \U1.addr[2] ;
  wire \U1.addr[3] ;
  wire \U1.addr[4] ;
  wire \U1.addr[5] ;
  wire \U1.addr[6] ;
  wire \U1.addr[7] ;
  wire \U1.count[0] ;
  wire \U1.count[1] ;
  wire \U1.count[2] ;
  wire \U1.fixed[0] ;
  wire \U1.fixed[1] ;
  wire \U1.fixed[2] ;
  wire \U1.ldata[0] ;
  wire \U1.ldata[1] ;
  wire \U1.ldata[2] ;
  wire \U1.ldata[3] ;
  wire \U1.ldata[4] ;
  wire \U1.ldata[5] ;
  wire \U1.ldata[6] ;
  wire \U1.odata[1] ;
  wire \U1.odata[2] ;
  wire \U1.odata[3] ;
  wire \U1.odata[4] ;
  wire \U1.odata[5] ;
  wire \U1.odata[6] ;
  wire \U1.odata[7] ;
  wire \U1.readmode ;
  wire \U1.state[0] ;
  wire \U1.state[1] ;
  wire \U1.state[2] ;
  wire \U1.writemode ;
  wire \U1.wrstb ;
  output irq;
  output [3:0] mask_rev;
  input [3:0] mask_rev_in;
  output [11:0] mfgr_id;
  output pll_bypass;
  output pll_dco_ena;
  output [4:0] pll_div;
  output [2:0] pll_sel;
  output [25:0] pll_trim;
  output [7:0] prod_id;
  output reg_ena;
  output reset;
  output sdo_enb;
  input trap;
  output xtal_ena;

// CTS added wires
wire clk_0_0;
wire clk_0_16;
wire clk_0_32;
wire clk_0_48;
wire clk_0_64;
wire clk_1_0;

// CTS added buffers
sky130_fd_sc_hd_clkbuf_4 _CTS_buf_1_0 ( 
	.A(clk_1_0),
	.X(clk_0_0)
);
sky130_fd_sc_hd_clkbuf_4 _CTS_buf_1_16 ( 
	.A(clk_1_0),
	.X(clk_0_16)
);
sky130_fd_sc_hd_clkbuf_4 _CTS_buf_1_32 ( 
	.A(clk_1_0),
	.X(clk_0_32)
);
sky130_fd_sc_hd_clkbuf_4 _CTS_buf_1_48 ( 
	.A(clk_1_0),
	.X(clk_0_48)
);
sky130_fd_sc_hd_clkbuf_4 _CTS_buf_1_64 ( 
	.A(clk_1_0),
	.X(clk_0_64)
);
sky130_fd_sc_hd_clkbuf_16 _CTS_root (
	.A(SCK ),
	.X(clk_1_0)
);

  sky130_fd_sc_hd_inv_4 _414_ (
    .A(CSB),
    .Y(_084_)
  );
  sky130_fd_sc_hd_buf_4 _415_ (
    .A(_084_),
    .X(_085_)
  );
  sky130_fd_sc_hd_buf_4 _416_ (
    .A(_085_),
    .X(_075_)
  );
  sky130_fd_sc_hd_inv_4 _417_ (
    .A(_083_),
    .Y(sdo_enb)
  );
  sky130_fd_sc_hd_and2_4 _418_ (
    .A(\U1.state[1] ),
    .B(\U1.readmode ),
    .X(_086_)
  );
  sky130_fd_sc_hd_buf_4 _419_ (
    .A(_086_),
    .X(_322_)
  );
  sky130_fd_sc_hd_inv_4 _420_ (
    .A(SCK),
    .Y(_087_)
  );
  sky130_fd_sc_hd_buf_4 _421_ (
    .A(_087_),
    .X(_411_)
  );
  sky130_fd_sc_hd_buf_4 _422_ (
    .A(_411_),
    .X(_412_)
  );
  sky130_fd_sc_hd_buf_4 _423_ (
    .A(_411_),
    .X(_413_)
  );
  sky130_fd_sc_hd_buf_4 _424_ (
    .A(_411_),
    .X(_076_)
  );
  sky130_fd_sc_hd_buf_4 _425_ (
    .A(_411_),
    .X(_077_)
  );
  sky130_fd_sc_hd_buf_4 _426_ (
    .A(_087_),
    .X(_088_)
  );
  sky130_fd_sc_hd_buf_4 _427_ (
    .A(_088_),
    .X(_078_)
  );
  sky130_fd_sc_hd_buf_4 _428_ (
    .A(_088_),
    .X(_079_)
  );
  sky130_fd_sc_hd_buf_4 _429_ (
    .A(_088_),
    .X(_080_)
  );
  sky130_fd_sc_hd_buf_4 _430_ (
    .A(_088_),
    .X(_081_)
  );
  sky130_fd_sc_hd_buf_4 _431_ (
    .A(_088_),
    .X(_082_)
  );
  sky130_fd_sc_hd_inv_4 _432_ (
    .A(\U1.state[2] ),
    .Y(_089_)
  );
  sky130_fd_sc_hd_buf_4 _433_ (
    .A(_089_),
    .X(_090_)
  );
  sky130_fd_sc_hd_buf_4 _434_ (
    .A(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd_buf_4 _435_ (
    .A(_091_),
    .X(_092_)
  );
  sky130_fd_sc_hd_inv_4 _436_ (
    .A(\U1.count[2] ),
    .Y(_093_)
  );
  sky130_fd_sc_hd_inv_4 _437_ (
    .A(\U1.count[0] ),
    .Y(_094_)
  );
  sky130_fd_sc_hd_inv_4 _438_ (
    .A(\U1.count[1] ),
    .Y(_095_)
  );
  sky130_fd_sc_hd_or3_4 _439_ (
    .A(_093_),
    .B(_094_),
    .C(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd_buf_4 _440_ (
    .A(_096_),
    .X(_097_)
  );
  sky130_fd_sc_hd_inv_4 _441_ (
    .A(\U1.state[1] ),
    .Y(_098_)
  );
  sky130_fd_sc_hd_buf_4 _442_ (
    .A(_098_),
    .X(_099_)
  );
  sky130_fd_sc_hd_inv_4 _443_ (
    .A(_097_),
    .Y(_100_)
  );
  sky130_fd_sc_hd_nor2_4 _444_ (
    .A(\U1.fixed[2] ),
    .B(\U1.fixed[1] ),
    .Y(_101_)
  );
  sky130_fd_sc_hd_and2_4 _445_ (
    .A(\U1.fixed[0] ),
    .B(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd_and2_4 _446_ (
    .A(_100_),
    .B(_102_),
    .X(_103_)
  );
  sky130_fd_sc_hd_o22ai_4 _447_ (
    .A1(_092_),
    .A2(_097_),
    .B1(_099_),
    .B2(_103_),
    .Y(_074_)
  );
  sky130_fd_sc_hd_inv_4 _448_ (
    .A(\U1.state[0] ),
    .Y(_104_)
  );
  sky130_fd_sc_hd_buf_4 _449_ (
    .A(_104_),
    .X(_105_)
  );
  sky130_fd_sc_hd_buf_4 _450_ (
    .A(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd_o22ai_4 _451_ (
    .A1(_092_),
    .A2(_100_),
    .B1(_106_),
    .B2(_097_),
    .Y(_040_)
  );
  sky130_fd_sc_hd_buf_4 _452_ (
    .A(\U1.state[0] ),
    .X(_107_)
  );
  sky130_fd_sc_hd_buf_4 _453_ (
    .A(_107_),
    .X(_108_)
  );
  sky130_fd_sc_hd_a32o_4 _454_ (
    .A1(\U1.state[1] ),
    .A2(_100_),
    .A3(_102_),
    .B1(_108_),
    .B2(_097_),
    .X(_058_)
  );
  sky130_fd_sc_hd_buf_4 _455_ (
    .A(\U1.wrstb ),
    .X(_109_)
  );
  sky130_fd_sc_hd_inv_4 _456_ (
    .A(\U1.addr[1] ),
    .Y(_110_)
  );
  sky130_fd_sc_hd_buf_4 _457_ (
    .A(\U1.state[2] ),
    .X(_111_)
  );
  sky130_fd_sc_hd_inv_4 _458_ (
    .A(\U1.addr[2] ),
    .Y(_112_)
  );
  sky130_fd_sc_hd_o22a_4 _459_ (
    .A1(_090_),
    .A2(_110_),
    .B1(_111_),
    .B2(_112_),
    .X(_113_)
  );
  sky130_fd_sc_hd_inv_4 _460_ (
    .A(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd_inv_4 _461_ (
    .A(\U1.addr[3] ),
    .Y(_115_)
  );
  sky130_fd_sc_hd_o22a_4 _462_ (
    .A1(_090_),
    .A2(_112_),
    .B1(_111_),
    .B2(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd_or2_4 _463_ (
    .A(_114_),
    .B(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd_inv_4 _464_ (
    .A(\U1.addr[0] ),
    .Y(_118_)
  );
  sky130_fd_sc_hd_buf_4 _465_ (
    .A(_118_),
    .X(_119_)
  );
  sky130_fd_sc_hd_o22a_4 _466_ (
    .A1(_090_),
    .A2(_119_),
    .B1(_111_),
    .B2(_110_),
    .X(_120_)
  );
  sky130_fd_sc_hd_inv_4 _467_ (
    .A(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd_and2_4 _468_ (
    .A(\U1.state[2] ),
    .B(\U1.addr[3] ),
    .X(_122_)
  );
  sky130_fd_sc_hd_a21o_4 _469_ (
    .A1(_089_),
    .A2(\U1.addr[7] ),
    .B1(\U1.addr[6] ),
    .X(_123_)
  );
  sky130_fd_sc_hd_or4_4 _470_ (
    .A(\U1.addr[4] ),
    .B(\U1.addr[5] ),
    .C(_122_),
    .D(_123_),
    .X(_124_)
  );
  sky130_fd_sc_hd_inv_4 _471_ (
    .A(SDI),
    .Y(_125_)
  );
  sky130_fd_sc_hd_o22a_4 _472_ (
    .A1(_089_),
    .A2(_125_),
    .B1(\U1.state[2] ),
    .B2(_118_),
    .X(_126_)
  );
  sky130_fd_sc_hd_or2_4 _473_ (
    .A(_124_),
    .B(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd_or2_4 _474_ (
    .A(_121_),
    .B(_127_),
    .X(_128_)
  );
  sky130_fd_sc_hd_or2_4 _475_ (
    .A(_117_),
    .B(_128_),
    .X(_129_)
  );
  sky130_fd_sc_hd_buf_4 _476_ (
    .A(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd_inv_4 _477_ (
    .A(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd_buf_4 _478_ (
    .A(_131_),
    .X(_132_)
  );
  sky130_fd_sc_hd_and2_4 _479_ (
    .A(_109_),
    .B(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd_buf_4 _480_ (
    .A(_133_),
    .X(_134_)
  );
  sky130_fd_sc_hd_buf_4 _481_ (
    .A(_130_),
    .X(_135_)
  );
  sky130_fd_sc_hd_buf_4 _482_ (
    .A(_135_),
    .X(_136_)
  );
  sky130_fd_sc_hd_buf_4 _483_ (
    .A(SDI),
    .X(_137_)
  );
  sky130_fd_sc_hd_inv_4 _484_ (
    .A(\U1.wrstb ),
    .Y(_138_)
  );
  sky130_fd_sc_hd_or2_4 _485_ (
    .A(_137_),
    .B(_138_),
    .X(_139_)
  );
  sky130_fd_sc_hd_buf_4 _486_ (
    .A(_139_),
    .X(_140_)
  );
  sky130_fd_sc_hd_o22a_4 _487_ (
    .A1(pll_trim[0]),
    .A2(_134_),
    .B1(_136_),
    .B2(_140_),
    .X(_011_)
  );
  sky130_fd_sc_hd_or2_4 _488_ (
    .A(_138_),
    .B(\U1.odata[1] ),
    .X(_141_)
  );
  sky130_fd_sc_hd_buf_4 _489_ (
    .A(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd_o22a_4 _490_ (
    .A1(pll_trim[1]),
    .A2(_134_),
    .B1(_136_),
    .B2(_142_),
    .X(_022_)
  );
  sky130_fd_sc_hd_or2_4 _491_ (
    .A(_138_),
    .B(\U1.odata[2] ),
    .X(_143_)
  );
  sky130_fd_sc_hd_buf_4 _492_ (
    .A(_143_),
    .X(_144_)
  );
  sky130_fd_sc_hd_o22a_4 _493_ (
    .A1(pll_trim[2]),
    .A2(_134_),
    .B1(_136_),
    .B2(_144_),
    .X(_029_)
  );
  sky130_fd_sc_hd_buf_4 _494_ (
    .A(_138_),
    .X(_145_)
  );
  sky130_fd_sc_hd_or2_4 _495_ (
    .A(_145_),
    .B(\U1.odata[3] ),
    .X(_146_)
  );
  sky130_fd_sc_hd_o22a_4 _496_ (
    .A1(pll_trim[3]),
    .A2(_134_),
    .B1(_136_),
    .B2(_146_),
    .X(_030_)
  );
  sky130_fd_sc_hd_or2_4 _497_ (
    .A(_145_),
    .B(\U1.odata[4] ),
    .X(_147_)
  );
  sky130_fd_sc_hd_o22a_4 _498_ (
    .A1(pll_trim[4]),
    .A2(_134_),
    .B1(_136_),
    .B2(_147_),
    .X(_031_)
  );
  sky130_fd_sc_hd_or2_4 _499_ (
    .A(_145_),
    .B(\U1.odata[5] ),
    .X(_148_)
  );
  sky130_fd_sc_hd_o22a_4 _500_ (
    .A1(pll_trim[5]),
    .A2(_133_),
    .B1(_135_),
    .B2(_148_),
    .X(_032_)
  );
  sky130_fd_sc_hd_or2_4 _501_ (
    .A(_145_),
    .B(\U1.odata[6] ),
    .X(_149_)
  );
  sky130_fd_sc_hd_o22a_4 _502_ (
    .A1(pll_trim[6]),
    .A2(_133_),
    .B1(_135_),
    .B2(_149_),
    .X(_033_)
  );
  sky130_fd_sc_hd_or2_4 _503_ (
    .A(_145_),
    .B(\U1.odata[7] ),
    .X(_150_)
  );
  sky130_fd_sc_hd_o22a_4 _504_ (
    .A1(pll_trim[7]),
    .A2(_133_),
    .B1(_135_),
    .B2(_150_),
    .X(_034_)
  );
  sky130_fd_sc_hd_buf_4 _505_ (
    .A(\U1.wrstb ),
    .X(_151_)
  );
  sky130_fd_sc_hd_inv_4 _506_ (
    .A(_116_),
    .Y(_152_)
  );
  sky130_fd_sc_hd_or2_4 _507_ (
    .A(_113_),
    .B(_152_),
    .X(_153_)
  );
  sky130_fd_sc_hd_inv_4 _508_ (
    .A(_126_),
    .Y(_154_)
  );
  sky130_fd_sc_hd_or3_4 _509_ (
    .A(_120_),
    .B(_154_),
    .C(_124_),
    .X(_155_)
  );
  sky130_fd_sc_hd_or2_4 _510_ (
    .A(_153_),
    .B(_155_),
    .X(_156_)
  );
  sky130_fd_sc_hd_inv_4 _511_ (
    .A(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd_and2_4 _512_ (
    .A(_151_),
    .B(_157_),
    .X(_158_)
  );
  sky130_fd_sc_hd_o22a_4 _513_ (
    .A1(irq),
    .A2(_158_),
    .B1(_140_),
    .B2(_156_),
    .X(_000_)
  );
  sky130_fd_sc_hd_or2_4 _514_ (
    .A(_128_),
    .B(_153_),
    .X(_159_)
  );
  sky130_fd_sc_hd_inv_4 _515_ (
    .A(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd_and2_4 _516_ (
    .A(_151_),
    .B(_160_),
    .X(_161_)
  );
  sky130_fd_sc_hd_o22a_4 _517_ (
    .A1(pll_bypass),
    .A2(_161_),
    .B1(_140_),
    .B2(_159_),
    .X(_001_)
  );
  sky130_fd_sc_hd_or2_4 _518_ (
    .A(_113_),
    .B(_116_),
    .X(_162_)
  );
  sky130_fd_sc_hd_or2_4 _519_ (
    .A(_155_),
    .B(_162_),
    .X(_163_)
  );
  sky130_fd_sc_hd_inv_4 _520_ (
    .A(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd_buf_4 _521_ (
    .A(_164_),
    .X(_165_)
  );
  sky130_fd_sc_hd_and2_4 _522_ (
    .A(_109_),
    .B(_165_),
    .X(_166_)
  );
  sky130_fd_sc_hd_buf_4 _523_ (
    .A(_166_),
    .X(_167_)
  );
  sky130_fd_sc_hd_buf_4 _524_ (
    .A(_163_),
    .X(_168_)
  );
  sky130_fd_sc_hd_o22a_4 _525_ (
    .A1(pll_div[0]),
    .A2(_167_),
    .B1(_140_),
    .B2(_168_),
    .X(_003_)
  );
  sky130_fd_sc_hd_o22a_4 _526_ (
    .A1(pll_div[1]),
    .A2(_167_),
    .B1(_142_),
    .B2(_168_),
    .X(_004_)
  );
  sky130_fd_sc_hd_o22a_4 _527_ (
    .A1(pll_div[2]),
    .A2(_167_),
    .B1(_144_),
    .B2(_168_),
    .X(_005_)
  );
  sky130_fd_sc_hd_o22a_4 _528_ (
    .A1(pll_div[3]),
    .A2(_167_),
    .B1(_146_),
    .B2(_168_),
    .X(_006_)
  );
  sky130_fd_sc_hd_o22a_4 _529_ (
    .A1(pll_div[4]),
    .A2(_167_),
    .B1(_147_),
    .B2(_168_),
    .X(_007_)
  );
  sky130_fd_sc_hd_or2_4 _530_ (
    .A(_128_),
    .B(_162_),
    .X(_169_)
  );
  sky130_fd_sc_hd_inv_4 _531_ (
    .A(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd_and2_4 _532_ (
    .A(_151_),
    .B(_170_),
    .X(_171_)
  );
  sky130_fd_sc_hd_buf_4 _533_ (
    .A(_169_),
    .X(_172_)
  );
  sky130_fd_sc_hd_o22a_4 _534_ (
    .A1(pll_sel[0]),
    .A2(_171_),
    .B1(_140_),
    .B2(_172_),
    .X(_008_)
  );
  sky130_fd_sc_hd_o22a_4 _535_ (
    .A1(pll_sel[1]),
    .A2(_171_),
    .B1(_142_),
    .B2(_172_),
    .X(_009_)
  );
  sky130_fd_sc_hd_o22a_4 _536_ (
    .A1(pll_sel[2]),
    .A2(_171_),
    .B1(_144_),
    .B2(_172_),
    .X(_010_)
  );
  sky130_fd_sc_hd_or2_4 _537_ (
    .A(_120_),
    .B(_127_),
    .X(_173_)
  );
  sky130_fd_sc_hd_or2_4 _538_ (
    .A(_153_),
    .B(_173_),
    .X(_174_)
  );
  sky130_fd_sc_hd_inv_4 _539_ (
    .A(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd_and2_4 _540_ (
    .A(_151_),
    .B(_175_),
    .X(_176_)
  );
  sky130_fd_sc_hd_buf_4 _541_ (
    .A(_139_),
    .X(_177_)
  );
  sky130_fd_sc_hd_o22a_4 _542_ (
    .A1(reset),
    .A2(_176_),
    .B1(_177_),
    .B2(_174_),
    .X(_038_)
  );
  sky130_fd_sc_hd_or3_4 _543_ (
    .A(_121_),
    .B(_154_),
    .C(_124_),
    .X(_178_)
  );
  sky130_fd_sc_hd_or2_4 _544_ (
    .A(_153_),
    .B(_178_),
    .X(_179_)
  );
  sky130_fd_sc_hd_inv_4 _545_ (
    .A(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd_and2_4 _546_ (
    .A(_109_),
    .B(_180_),
    .X(_181_)
  );
  sky130_fd_sc_hd_buf_4 _547_ (
    .A(_179_),
    .X(_182_)
  );
  sky130_fd_sc_hd_o22a_4 _548_ (
    .A1(pll_dco_ena),
    .A2(_181_),
    .B1(_144_),
    .B2(_182_),
    .X(_002_)
  );
  sky130_fd_sc_hd_o22a_4 _549_ (
    .A1(reg_ena),
    .A2(_181_),
    .B1(_142_),
    .B2(_182_),
    .X(_037_)
  );
  sky130_fd_sc_hd_o22a_4 _550_ (
    .A1(xtal_ena),
    .A2(_181_),
    .B1(_177_),
    .B2(_182_),
    .X(_039_)
  );
  sky130_fd_sc_hd_and2_4 _551_ (
    .A(_094_),
    .B(_095_),
    .X(_183_)
  );
  sky130_fd_sc_hd_and2_4 _552_ (
    .A(_093_),
    .B(_183_),
    .X(_184_)
  );
  sky130_fd_sc_hd_buf_4 _553_ (
    .A(_184_),
    .X(_185_)
  );
  sky130_fd_sc_hd_buf_4 _554_ (
    .A(_185_),
    .X(_186_)
  );
  sky130_fd_sc_hd_or2_4 _555_ (
    .A(_114_),
    .B(_152_),
    .X(_187_)
  );
  sky130_fd_sc_hd_buf_4 _556_ (
    .A(_187_),
    .X(_188_)
  );
  sky130_fd_sc_hd_nor2_4 _557_ (
    .A(_173_),
    .B(_188_),
    .Y(_189_)
  );
  sky130_fd_sc_hd_or2_4 _558_ (
    .A(pll_bypass),
    .B(_159_),
    .X(_190_)
  );
  sky130_fd_sc_hd_or2_4 _559_ (
    .A(reset),
    .B(_174_),
    .X(_191_)
  );
  sky130_fd_sc_hd_or2_4 _560_ (
    .A(_117_),
    .B(_178_),
    .X(_192_)
  );
  sky130_fd_sc_hd_inv_4 _561_ (
    .A(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd_or2_4 _562_ (
    .A(pll_trim[0]),
    .B(_130_),
    .X(_194_)
  );
  sky130_fd_sc_hd_or2_4 _563_ (
    .A(_117_),
    .B(_155_),
    .X(_195_)
  );
  sky130_fd_sc_hd_buf_4 _564_ (
    .A(_195_),
    .X(_196_)
  );
  sky130_fd_sc_hd_inv_4 _565_ (
    .A(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd_or2_4 _566_ (
    .A(_117_),
    .B(_173_),
    .X(_198_)
  );
  sky130_fd_sc_hd_buf_4 _567_ (
    .A(_198_),
    .X(_199_)
  );
  sky130_fd_sc_hd_or2_4 _568_ (
    .A(pll_trim[16]),
    .B(_199_),
    .X(_200_)
  );
  sky130_fd_sc_hd_or2_4 _569_ (
    .A(_162_),
    .B(_178_),
    .X(_201_)
  );
  sky130_fd_sc_hd_buf_4 _570_ (
    .A(_201_),
    .X(_202_)
  );
  sky130_fd_sc_hd_inv_4 _571_ (
    .A(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd_inv_4 _572_ (
    .A(_198_),
    .Y(_204_)
  );
  sky130_fd_sc_hd_a21o_4 _573_ (
    .A1(pll_div[0]),
    .A2(_164_),
    .B1(_170_),
    .X(_205_)
  );
  sky130_fd_sc_hd_or2_4 _574_ (
    .A(pll_sel[0]),
    .B(_169_),
    .X(_206_)
  );
  sky130_fd_sc_hd_and3_4 _575_ (
    .A(_202_),
    .B(_205_),
    .C(_206_),
    .X(_207_)
  );
  sky130_fd_sc_hd_a211o_4 _576_ (
    .A1(pll_trim[24]),
    .A2(_203_),
    .B1(_204_),
    .C1(_207_),
    .X(_208_)
  );
  sky130_fd_sc_hd_and3_4 _577_ (
    .A(_195_),
    .B(_200_),
    .C(_208_),
    .X(_209_)
  );
  sky130_fd_sc_hd_a211o_4 _578_ (
    .A1(pll_trim[8]),
    .A2(_197_),
    .B1(_131_),
    .C1(_209_),
    .X(_210_)
  );
  sky130_fd_sc_hd_and3_4 _579_ (
    .A(_192_),
    .B(_194_),
    .C(_210_),
    .X(_211_)
  );
  sky130_fd_sc_hd_a211o_4 _580_ (
    .A1(trap),
    .A2(_193_),
    .B1(_175_),
    .C1(_211_),
    .X(_212_)
  );
  sky130_fd_sc_hd_and3_4 _581_ (
    .A(_156_),
    .B(_191_),
    .C(_212_),
    .X(_213_)
  );
  sky130_fd_sc_hd_a211o_4 _582_ (
    .A1(irq),
    .A2(_157_),
    .B1(_160_),
    .C1(_213_),
    .X(_214_)
  );
  sky130_fd_sc_hd_and3_4 _583_ (
    .A(_182_),
    .B(_190_),
    .C(_214_),
    .X(_215_)
  );
  sky130_fd_sc_hd_a211o_4 _584_ (
    .A1(pll_dco_ena),
    .A2(_180_),
    .B1(_189_),
    .C1(_215_),
    .X(_216_)
  );
  sky130_fd_sc_hd_inv_4 _585_ (
    .A(_086_),
    .Y(_217_)
  );
  sky130_fd_sc_hd_buf_4 _586_ (
    .A(_217_),
    .X(_218_)
  );
  sky130_fd_sc_hd_a32o_4 _587_ (
    .A1(_322_),
    .A2(_186_),
    .A3(_216_),
    .B1(\U1.ldata[0] ),
    .B2(_218_),
    .X(_041_)
  );
  sky130_fd_sc_hd_or2_4 _588_ (
    .A(\U1.ldata[0] ),
    .B(_185_),
    .X(_219_)
  );
  sky130_fd_sc_hd_inv_4 _589_ (
    .A(_184_),
    .Y(_220_)
  );
  sky130_fd_sc_hd_nor2_4 _590_ (
    .A(_155_),
    .B(_188_),
    .Y(_221_)
  );
  sky130_fd_sc_hd_or2_4 _591_ (
    .A(_220_),
    .B(_221_),
    .X(_222_)
  );
  sky130_fd_sc_hd_or2_4 _592_ (
    .A(pll_trim[1]),
    .B(_130_),
    .X(_223_)
  );
  sky130_fd_sc_hd_buf_4 _593_ (
    .A(_197_),
    .X(_224_)
  );
  sky130_fd_sc_hd_or2_4 _594_ (
    .A(pll_trim[17]),
    .B(_199_),
    .X(_225_)
  );
  sky130_fd_sc_hd_a21o_4 _595_ (
    .A1(pll_div[1]),
    .A2(_165_),
    .B1(_170_),
    .X(_226_)
  );
  sky130_fd_sc_hd_or2_4 _596_ (
    .A(pll_sel[1]),
    .B(_172_),
    .X(_227_)
  );
  sky130_fd_sc_hd_and3_4 _597_ (
    .A(_202_),
    .B(_226_),
    .C(_227_),
    .X(_228_)
  );
  sky130_fd_sc_hd_a211o_4 _598_ (
    .A1(pll_trim[25]),
    .A2(_203_),
    .B1(_204_),
    .C1(_228_),
    .X(_229_)
  );
  sky130_fd_sc_hd_and3_4 _599_ (
    .A(_196_),
    .B(_225_),
    .C(_229_),
    .X(_230_)
  );
  sky130_fd_sc_hd_a211o_4 _600_ (
    .A1(pll_trim[9]),
    .A2(_224_),
    .B1(_131_),
    .C1(_230_),
    .X(_231_)
  );
  sky130_fd_sc_hd_and3_4 _601_ (
    .A(_182_),
    .B(_223_),
    .C(_231_),
    .X(_232_)
  );
  sky130_fd_sc_hd_a211o_4 _602_ (
    .A1(reg_ena),
    .A2(_180_),
    .B1(_222_),
    .C1(_232_),
    .X(_233_)
  );
  sky130_fd_sc_hd_a32o_4 _603_ (
    .A1(_086_),
    .A2(_219_),
    .A3(_233_),
    .B1(\U1.ldata[1] ),
    .B2(_218_),
    .X(_042_)
  );
  sky130_fd_sc_hd_buf_4 _604_ (
    .A(_218_),
    .X(_234_)
  );
  sky130_fd_sc_hd_and2_4 _605_ (
    .A(pll_sel[2]),
    .B(_170_),
    .X(_235_)
  );
  sky130_fd_sc_hd_and3_4 _606_ (
    .A(pll_div[2]),
    .B(_165_),
    .C(_172_),
    .X(_236_)
  );
  sky130_fd_sc_hd_o32a_4 _607_ (
    .A1(_204_),
    .A2(_235_),
    .A3(_236_),
    .B1(pll_trim[18]),
    .B2(_199_),
    .X(_237_)
  );
  sky130_fd_sc_hd_buf_4 _608_ (
    .A(_196_),
    .X(_238_)
  );
  sky130_fd_sc_hd_buf_4 _609_ (
    .A(_238_),
    .X(_239_)
  );
  sky130_fd_sc_hd_o22ai_4 _610_ (
    .A1(_224_),
    .A2(_237_),
    .B1(pll_trim[10]),
    .B2(_239_),
    .Y(_240_)
  );
  sky130_fd_sc_hd_buf_4 _611_ (
    .A(_130_),
    .X(_241_)
  );
  sky130_fd_sc_hd_nor2_4 _612_ (
    .A(pll_trim[2]),
    .B(_241_),
    .Y(_242_)
  );
  sky130_fd_sc_hd_a211o_4 _613_ (
    .A1(_135_),
    .A2(_240_),
    .B1(_180_),
    .C1(_242_),
    .X(_243_)
  );
  sky130_fd_sc_hd_inv_4 _614_ (
    .A(_243_),
    .Y(_244_)
  );
  sky130_fd_sc_hd_nor2_4 _615_ (
    .A(_127_),
    .B(_188_),
    .Y(_245_)
  );
  sky130_fd_sc_hd_a211o_4 _616_ (
    .A1(xtal_ena),
    .A2(_180_),
    .B1(_222_),
    .C1(_245_),
    .X(_246_)
  );
  sky130_fd_sc_hd_o22a_4 _617_ (
    .A1(\U1.ldata[1] ),
    .A2(_186_),
    .B1(_244_),
    .B2(_246_),
    .X(_247_)
  );
  sky130_fd_sc_hd_o22a_4 _618_ (
    .A1(_234_),
    .A2(_247_),
    .B1(\U1.ldata[2] ),
    .B2(_322_),
    .X(_043_)
  );
  sky130_fd_sc_hd_a32oi_4 _619_ (
    .A1(pll_div[3]),
    .A2(_165_),
    .A3(_199_),
    .B1(pll_trim[19]),
    .B2(_204_),
    .Y(_248_)
  );
  sky130_fd_sc_hd_inv_4 _620_ (
    .A(pll_trim[11]),
    .Y(_249_)
  );
  sky130_fd_sc_hd_o22a_4 _621_ (
    .A1(_224_),
    .A2(_248_),
    .B1(_249_),
    .B2(_238_),
    .X(_250_)
  );
  sky130_fd_sc_hd_inv_4 _622_ (
    .A(pll_trim[3]),
    .Y(_251_)
  );
  sky130_fd_sc_hd_o22a_4 _623_ (
    .A1(_132_),
    .A2(_250_),
    .B1(_251_),
    .B2(_241_),
    .X(_252_)
  );
  sky130_fd_sc_hd_inv_4 _624_ (
    .A(\U1.ldata[2] ),
    .Y(_253_)
  );
  sky130_fd_sc_hd_o22a_4 _625_ (
    .A1(_220_),
    .A2(_252_),
    .B1(_253_),
    .B2(_185_),
    .X(_254_)
  );
  sky130_fd_sc_hd_or2_4 _626_ (
    .A(_218_),
    .B(_254_),
    .X(_255_)
  );
  sky130_fd_sc_hd_a21bo_4 _627_ (
    .A1(\U1.ldata[3] ),
    .A2(_234_),
    .B1N(_255_),
    .X(_044_)
  );
  sky130_fd_sc_hd_or2_4 _628_ (
    .A(_128_),
    .B(_188_),
    .X(_256_)
  );
  sky130_fd_sc_hd_or2_4 _629_ (
    .A(mask_rev_in[0]),
    .B(_256_),
    .X(_257_)
  );
  sky130_fd_sc_hd_inv_4 _630_ (
    .A(_256_),
    .Y(_258_)
  );
  sky130_fd_sc_hd_or2_4 _631_ (
    .A(_221_),
    .B(_258_),
    .X(_259_)
  );
  sky130_fd_sc_hd_buf_4 _632_ (
    .A(_204_),
    .X(_260_)
  );
  sky130_fd_sc_hd_and2_4 _633_ (
    .A(pll_div[4]),
    .B(_165_),
    .X(_261_)
  );
  sky130_fd_sc_hd_buf_4 _634_ (
    .A(_199_),
    .X(_262_)
  );
  sky130_fd_sc_hd_o22ai_4 _635_ (
    .A1(_260_),
    .A2(_261_),
    .B1(pll_trim[20]),
    .B2(_262_),
    .Y(_263_)
  );
  sky130_fd_sc_hd_nor2_4 _636_ (
    .A(pll_trim[12]),
    .B(_238_),
    .Y(_264_)
  );
  sky130_fd_sc_hd_a211o_4 _637_ (
    .A1(_238_),
    .A2(_263_),
    .B1(_132_),
    .C1(_264_),
    .X(_265_)
  );
  sky130_fd_sc_hd_inv_4 _638_ (
    .A(_265_),
    .Y(_266_)
  );
  sky130_fd_sc_hd_a211o_4 _639_ (
    .A1(pll_trim[4]),
    .A2(_132_),
    .B1(_259_),
    .C1(_266_),
    .X(_267_)
  );
  sky130_fd_sc_hd_buf_4 _640_ (
    .A(_220_),
    .X(_268_)
  );
  sky130_fd_sc_hd_a32oi_4 _641_ (
    .A1(_186_),
    .A2(_257_),
    .A3(_267_),
    .B1(\U1.ldata[3] ),
    .B2(_268_),
    .Y(_269_)
  );
  sky130_fd_sc_hd_inv_4 _642_ (
    .A(\U1.ldata[4] ),
    .Y(_270_)
  );
  sky130_fd_sc_hd_o22ai_4 _643_ (
    .A1(_234_),
    .A2(_269_),
    .B1(_270_),
    .B2(_322_),
    .Y(_045_)
  );
  sky130_fd_sc_hd_or2_4 _644_ (
    .A(mask_rev_in[1]),
    .B(_256_),
    .X(_271_)
  );
  sky130_fd_sc_hd_a32o_4 _645_ (
    .A1(pll_trim[21]),
    .A2(_238_),
    .A3(_260_),
    .B1(pll_trim[13]),
    .B2(_197_),
    .X(_272_)
  );
  sky130_fd_sc_hd_and2_4 _646_ (
    .A(pll_trim[5]),
    .B(_131_),
    .X(_273_)
  );
  sky130_fd_sc_hd_a211o_4 _647_ (
    .A1(_241_),
    .A2(_272_),
    .B1(_258_),
    .C1(_273_),
    .X(_274_)
  );
  sky130_fd_sc_hd_a32oi_4 _648_ (
    .A1(_185_),
    .A2(_271_),
    .A3(_274_),
    .B1(\U1.ldata[4] ),
    .B2(_268_),
    .Y(_275_)
  );
  sky130_fd_sc_hd_or2_4 _649_ (
    .A(_217_),
    .B(_275_),
    .X(_276_)
  );
  sky130_fd_sc_hd_a21bo_4 _650_ (
    .A1(\U1.ldata[5] ),
    .A2(_234_),
    .B1N(_276_),
    .X(_046_)
  );
  sky130_fd_sc_hd_or2_4 _651_ (
    .A(mask_rev_in[2]),
    .B(_256_),
    .X(_277_)
  );
  sky130_fd_sc_hd_a32o_4 _652_ (
    .A1(pll_trim[22]),
    .A2(_196_),
    .A3(_260_),
    .B1(pll_trim[14]),
    .B2(_197_),
    .X(_278_)
  );
  sky130_fd_sc_hd_and2_4 _653_ (
    .A(pll_trim[6]),
    .B(_131_),
    .X(_279_)
  );
  sky130_fd_sc_hd_a211o_4 _654_ (
    .A1(_241_),
    .A2(_278_),
    .B1(_259_),
    .C1(_279_),
    .X(_280_)
  );
  sky130_fd_sc_hd_a32oi_4 _655_ (
    .A1(_185_),
    .A2(_277_),
    .A3(_280_),
    .B1(\U1.ldata[5] ),
    .B2(_268_),
    .Y(_281_)
  );
  sky130_fd_sc_hd_or2_4 _656_ (
    .A(_217_),
    .B(_281_),
    .X(_282_)
  );
  sky130_fd_sc_hd_a21bo_4 _657_ (
    .A1(\U1.ldata[6] ),
    .A2(_234_),
    .B1N(_282_),
    .X(_047_)
  );
  sky130_fd_sc_hd_and2_4 _658_ (
    .A(\U1.ldata[6] ),
    .B(_268_),
    .X(_283_)
  );
  sky130_fd_sc_hd_and2_4 _659_ (
    .A(mask_rev_in[3]),
    .B(_258_),
    .X(_284_)
  );
  sky130_fd_sc_hd_or2_4 _660_ (
    .A(pll_trim[7]),
    .B(_241_),
    .X(_285_)
  );
  sky130_fd_sc_hd_and3_4 _661_ (
    .A(pll_trim[23]),
    .B(_196_),
    .C(_260_),
    .X(_286_)
  );
  sky130_fd_sc_hd_a211o_4 _662_ (
    .A1(pll_trim[15]),
    .A2(_224_),
    .B1(_132_),
    .C1(_286_),
    .X(_287_)
  );
  sky130_fd_sc_hd_and3_4 _663_ (
    .A(_256_),
    .B(_285_),
    .C(_287_),
    .X(_288_)
  );
  sky130_fd_sc_hd_o21a_4 _664_ (
    .A1(_284_),
    .A2(_288_),
    .B1(_186_),
    .X(_289_)
  );
  sky130_fd_sc_hd_o32a_4 _665_ (
    .A1(_218_),
    .A2(_283_),
    .A3(_289_),
    .B1(SDO),
    .B2(_322_),
    .X(_048_)
  );
  sky130_fd_sc_hd_buf_4 _666_ (
    .A(_107_),
    .X(_290_)
  );
  sky130_fd_sc_hd_or2_4 _667_ (
    .A(_099_),
    .B(_097_),
    .X(_291_)
  );
  sky130_fd_sc_hd_o21ai_4 _668_ (
    .A1(_102_),
    .A2(_291_),
    .B1(_119_),
    .Y(_292_)
  );
  sky130_fd_sc_hd_or4_4 _669_ (
    .A(_098_),
    .B(_096_),
    .C(_102_),
    .D(_119_),
    .X(_293_)
  );
  sky130_fd_sc_hd_buf_4 _670_ (
    .A(_111_),
    .X(_294_)
  );
  sky130_fd_sc_hd_buf_4 _671_ (
    .A(_294_),
    .X(_295_)
  );
  sky130_fd_sc_hd_a32oi_4 _672_ (
    .A1(_092_),
    .A2(_292_),
    .A3(_293_),
    .B1(_295_),
    .B2(_137_),
    .Y(_296_)
  );
  sky130_fd_sc_hd_o22ai_4 _673_ (
    .A1(_290_),
    .A2(_296_),
    .B1(_106_),
    .B2(_119_),
    .Y(_049_)
  );
  sky130_fd_sc_hd_buf_4 _674_ (
    .A(_105_),
    .X(_297_)
  );
  sky130_fd_sc_hd_o21a_4 _675_ (
    .A1(_295_),
    .A2(_110_),
    .B1(_293_),
    .X(_298_)
  );
  sky130_fd_sc_hd_or2_4 _676_ (
    .A(_110_),
    .B(_293_),
    .X(_299_)
  );
  sky130_fd_sc_hd_inv_4 _677_ (
    .A(_299_),
    .Y(_300_)
  );
  sky130_fd_sc_hd_o22a_4 _678_ (
    .A1(_091_),
    .A2(_119_),
    .B1(_298_),
    .B2(_300_),
    .X(_301_)
  );
  sky130_fd_sc_hd_o22ai_4 _679_ (
    .A1(_297_),
    .A2(_110_),
    .B1(_290_),
    .B2(_301_),
    .Y(_050_)
  );
  sky130_fd_sc_hd_or2_4 _680_ (
    .A(\U1.addr[2] ),
    .B(_300_),
    .X(_302_)
  );
  sky130_fd_sc_hd_or2_4 _681_ (
    .A(_112_),
    .B(_299_),
    .X(_303_)
  );
  sky130_fd_sc_hd_a32oi_4 _682_ (
    .A1(_092_),
    .A2(_302_),
    .A3(_303_),
    .B1(_295_),
    .B2(\U1.addr[1] ),
    .Y(_304_)
  );
  sky130_fd_sc_hd_o22ai_4 _683_ (
    .A1(_290_),
    .A2(_304_),
    .B1(_106_),
    .B2(_112_),
    .Y(_051_)
  );
  sky130_fd_sc_hd_o21a_4 _684_ (
    .A1(_294_),
    .A2(_115_),
    .B1(_303_),
    .X(_305_)
  );
  sky130_fd_sc_hd_or2_4 _685_ (
    .A(_115_),
    .B(_303_),
    .X(_306_)
  );
  sky130_fd_sc_hd_inv_4 _686_ (
    .A(_306_),
    .Y(_307_)
  );
  sky130_fd_sc_hd_o22a_4 _687_ (
    .A1(_091_),
    .A2(_112_),
    .B1(_305_),
    .B2(_307_),
    .X(_308_)
  );
  sky130_fd_sc_hd_o22ai_4 _688_ (
    .A1(_297_),
    .A2(_115_),
    .B1(_290_),
    .B2(_308_),
    .Y(_052_)
  );
  sky130_fd_sc_hd_inv_4 _689_ (
    .A(\U1.addr[4] ),
    .Y(_309_)
  );
  sky130_fd_sc_hd_or2_4 _690_ (
    .A(_309_),
    .B(_306_),
    .X(_310_)
  );
  sky130_fd_sc_hd_or2_4 _691_ (
    .A(\U1.addr[4] ),
    .B(_307_),
    .X(_311_)
  );
  sky130_fd_sc_hd_and3_4 _692_ (
    .A(_091_),
    .B(_310_),
    .C(_311_),
    .X(_312_)
  );
  sky130_fd_sc_hd_nor2_4 _693_ (
    .A(_122_),
    .B(_312_),
    .Y(_313_)
  );
  sky130_fd_sc_hd_o22ai_4 _694_ (
    .A1(_290_),
    .A2(_313_),
    .B1(_106_),
    .B2(_309_),
    .Y(_053_)
  );
  sky130_fd_sc_hd_inv_4 _695_ (
    .A(\U1.addr[5] ),
    .Y(_314_)
  );
  sky130_fd_sc_hd_o21a_4 _696_ (
    .A1(_294_),
    .A2(_314_),
    .B1(_310_),
    .X(_315_)
  );
  sky130_fd_sc_hd_or2_4 _697_ (
    .A(_314_),
    .B(_310_),
    .X(_316_)
  );
  sky130_fd_sc_hd_inv_4 _698_ (
    .A(_316_),
    .Y(_317_)
  );
  sky130_fd_sc_hd_o22a_4 _699_ (
    .A1(_315_),
    .A2(_317_),
    .B1(_091_),
    .B2(_309_),
    .X(_318_)
  );
  sky130_fd_sc_hd_o22ai_4 _700_ (
    .A1(_108_),
    .A2(_318_),
    .B1(_106_),
    .B2(_314_),
    .Y(_054_)
  );
  sky130_fd_sc_hd_inv_4 _701_ (
    .A(\U1.addr[6] ),
    .Y(_319_)
  );
  sky130_fd_sc_hd_or2_4 _702_ (
    .A(_319_),
    .B(_316_),
    .X(_320_)
  );
  sky130_fd_sc_hd_or2_4 _703_ (
    .A(\U1.addr[6] ),
    .B(_317_),
    .X(_321_)
  );
  sky130_fd_sc_hd_a32oi_4 _704_ (
    .A1(_092_),
    .A2(_320_),
    .A3(_321_),
    .B1(_295_),
    .B2(\U1.addr[5] ),
    .Y(_323_)
  );
  sky130_fd_sc_hd_o22ai_4 _705_ (
    .A1(_108_),
    .A2(_323_),
    .B1(_297_),
    .B2(_319_),
    .Y(_055_)
  );
  sky130_fd_sc_hd_nor2_4 _706_ (
    .A(\U1.addr[7] ),
    .B(_316_),
    .Y(_324_)
  );
  sky130_fd_sc_hd_a211o_4 _707_ (
    .A1(\U1.addr[7] ),
    .A2(_320_),
    .B1(_295_),
    .C1(_324_),
    .X(_325_)
  );
  sky130_fd_sc_hd_a32o_4 _708_ (
    .A1(_297_),
    .A2(_123_),
    .A3(_325_),
    .B1(_108_),
    .B2(\U1.addr[7] ),
    .X(_056_)
  );
  sky130_fd_sc_hd_and3_4 _709_ (
    .A(_099_),
    .B(_090_),
    .C(_104_),
    .X(_326_)
  );
  sky130_fd_sc_hd_or2_4 _710_ (
    .A(_094_),
    .B(_326_),
    .X(_327_)
  );
  sky130_fd_sc_hd_inv_4 _711_ (
    .A(_327_),
    .Y(_328_)
  );
  sky130_fd_sc_hd_a21oi_4 _712_ (
    .A1(_094_),
    .A2(_326_),
    .B1(_328_),
    .Y(_057_)
  );
  sky130_fd_sc_hd_or2_4 _713_ (
    .A(_095_),
    .B(_327_),
    .X(_329_)
  );
  sky130_fd_sc_hd_o21a_4 _714_ (
    .A1(\U1.count[1] ),
    .A2(_328_),
    .B1(_329_),
    .X(_059_)
  );
  sky130_fd_sc_hd_a32o_4 _715_ (
    .A1(\U1.count[1] ),
    .A2(_328_),
    .A3(_093_),
    .B1(\U1.count[2] ),
    .B2(_329_),
    .X(_060_)
  );
  sky130_fd_sc_hd_or2_4 _716_ (
    .A(_105_),
    .B(_268_),
    .X(_330_)
  );
  sky130_fd_sc_hd_a32o_4 _717_ (
    .A1(_108_),
    .A2(_186_),
    .A3(_137_),
    .B1(\U1.writemode ),
    .B2(_330_),
    .X(_061_)
  );
  sky130_fd_sc_hd_or4_4 _718_ (
    .A(\U1.count[2] ),
    .B(\U1.count[1] ),
    .C(_105_),
    .D(_183_),
    .X(_331_)
  );
  sky130_fd_sc_hd_or2_4 _719_ (
    .A(_125_),
    .B(_331_),
    .X(_332_)
  );
  sky130_fd_sc_hd_a21bo_4 _720_ (
    .A1(\U1.readmode ),
    .A2(_331_),
    .B1N(_332_),
    .X(_062_)
  );
  sky130_fd_sc_hd_buf_4 _721_ (
    .A(\U1.fixed[0] ),
    .X(_333_)
  );
  sky130_fd_sc_hd_or4_4 _722_ (
    .A(_099_),
    .B(_294_),
    .C(_096_),
    .D(_101_),
    .X(_334_)
  );
  sky130_fd_sc_hd_inv_4 _723_ (
    .A(_334_),
    .Y(_335_)
  );
  sky130_fd_sc_hd_or2_4 _724_ (
    .A(_333_),
    .B(_335_),
    .X(_336_)
  );
  sky130_fd_sc_hd_nand2_4 _725_ (
    .A(_333_),
    .B(_335_),
    .Y(_337_)
  );
  sky130_fd_sc_hd_o22a_4 _726_ (
    .A1(\U1.count[2] ),
    .A2(\U1.count[1] ),
    .B1(_093_),
    .B2(_183_),
    .X(_338_)
  );
  sky130_fd_sc_hd_inv_4 _727_ (
    .A(_338_),
    .Y(_339_)
  );
  sky130_fd_sc_hd_or2_4 _728_ (
    .A(_137_),
    .B(_339_),
    .X(_340_)
  );
  sky130_fd_sc_hd_o21a_4 _729_ (
    .A1(_333_),
    .A2(_338_),
    .B1(_107_),
    .X(_341_)
  );
  sky130_fd_sc_hd_a32o_4 _730_ (
    .A1(_297_),
    .A2(_336_),
    .A3(_337_),
    .B1(_340_),
    .B2(_341_),
    .X(_063_)
  );
  sky130_fd_sc_hd_or2_4 _731_ (
    .A(\U1.fixed[1] ),
    .B(_338_),
    .X(_342_)
  );
  sky130_fd_sc_hd_or2_4 _732_ (
    .A(_333_),
    .B(_339_),
    .X(_343_)
  );
  sky130_fd_sc_hd_or4_4 _733_ (
    .A(_098_),
    .B(_111_),
    .C(_096_),
    .D(_333_),
    .X(_344_)
  );
  sky130_fd_sc_hd_inv_4 _734_ (
    .A(_344_),
    .Y(_345_)
  );
  sky130_fd_sc_hd_or2_4 _735_ (
    .A(\U1.fixed[1] ),
    .B(_345_),
    .X(_346_)
  );
  sky130_fd_sc_hd_a211o_4 _736_ (
    .A1(\U1.fixed[1] ),
    .A2(_345_),
    .B1(_107_),
    .C1(_101_),
    .X(_347_)
  );
  sky130_fd_sc_hd_inv_4 _737_ (
    .A(_347_),
    .Y(_348_)
  );
  sky130_fd_sc_hd_a32o_4 _738_ (
    .A1(_107_),
    .A2(_342_),
    .A3(_343_),
    .B1(_346_),
    .B2(_348_),
    .X(_064_)
  );
  sky130_fd_sc_hd_and2_4 _739_ (
    .A(\U1.state[0] ),
    .B(_338_),
    .X(_349_)
  );
  sky130_fd_sc_hd_a21oi_4 _740_ (
    .A1(_105_),
    .A2(_345_),
    .B1(_349_),
    .Y(_350_)
  );
  sky130_fd_sc_hd_o22a_4 _741_ (
    .A1(\U1.fixed[1] ),
    .A2(_350_),
    .B1(\U1.fixed[2] ),
    .B2(_349_),
    .X(_065_)
  );
  sky130_fd_sc_hd_or3_4 _742_ (
    .A(_099_),
    .B(_294_),
    .C(\U1.state[0] ),
    .X(_351_)
  );
  sky130_fd_sc_hd_inv_4 _743_ (
    .A(_351_),
    .Y(_352_)
  );
  sky130_fd_sc_hd_buf_4 _744_ (
    .A(_352_),
    .X(_353_)
  );
  sky130_fd_sc_hd_buf_4 _745_ (
    .A(_351_),
    .X(_355_)
  );
  sky130_fd_sc_hd_and2_4 _746_ (
    .A(\U1.odata[1] ),
    .B(_355_),
    .X(_357_)
  );
  sky130_fd_sc_hd_a21o_4 _747_ (
    .A1(_137_),
    .A2(_353_),
    .B1(_357_),
    .X(_066_)
  );
  sky130_fd_sc_hd_and2_4 _748_ (
    .A(\U1.odata[2] ),
    .B(_355_),
    .X(_360_)
  );
  sky130_fd_sc_hd_a21o_4 _749_ (
    .A1(\U1.odata[1] ),
    .A2(_353_),
    .B1(_360_),
    .X(_067_)
  );
  sky130_fd_sc_hd_and2_4 _750_ (
    .A(\U1.odata[3] ),
    .B(_355_),
    .X(_363_)
  );
  sky130_fd_sc_hd_a21o_4 _751_ (
    .A1(\U1.odata[2] ),
    .A2(_353_),
    .B1(_363_),
    .X(_068_)
  );
  sky130_fd_sc_hd_and2_4 _752_ (
    .A(\U1.odata[4] ),
    .B(_355_),
    .X(_366_)
  );
  sky130_fd_sc_hd_a21o_4 _753_ (
    .A1(\U1.odata[3] ),
    .A2(_353_),
    .B1(_366_),
    .X(_069_)
  );
  sky130_fd_sc_hd_and2_4 _754_ (
    .A(\U1.odata[5] ),
    .B(_355_),
    .X(_369_)
  );
  sky130_fd_sc_hd_a21o_4 _755_ (
    .A1(\U1.odata[4] ),
    .A2(_353_),
    .B1(_369_),
    .X(_070_)
  );
  sky130_fd_sc_hd_and2_4 _756_ (
    .A(\U1.odata[6] ),
    .B(_351_),
    .X(_372_)
  );
  sky130_fd_sc_hd_a21o_4 _757_ (
    .A1(\U1.odata[5] ),
    .A2(_352_),
    .B1(_372_),
    .X(_071_)
  );
  sky130_fd_sc_hd_and2_4 _758_ (
    .A(\U1.odata[7] ),
    .B(_351_),
    .X(_375_)
  );
  sky130_fd_sc_hd_a21o_4 _759_ (
    .A1(\U1.odata[6] ),
    .A2(_352_),
    .B1(_375_),
    .X(_072_)
  );
  sky130_fd_sc_hd_and2_4 _760_ (
    .A(_151_),
    .B(_203_),
    .X(_378_)
  );
  sky130_fd_sc_hd_o22a_4 _761_ (
    .A1(pll_trim[24]),
    .A2(_378_),
    .B1(_177_),
    .B2(_202_),
    .X(_027_)
  );
  sky130_fd_sc_hd_o22a_4 _762_ (
    .A1(pll_trim[25]),
    .A2(_378_),
    .B1(_142_),
    .B2(_202_),
    .X(_028_)
  );
  sky130_fd_sc_hd_and2_4 _763_ (
    .A(_109_),
    .B(_260_),
    .X(_382_)
  );
  sky130_fd_sc_hd_buf_4 _764_ (
    .A(_382_),
    .X(_384_)
  );
  sky130_fd_sc_hd_buf_4 _765_ (
    .A(_262_),
    .X(_386_)
  );
  sky130_fd_sc_hd_o22a_4 _766_ (
    .A1(pll_trim[16]),
    .A2(_384_),
    .B1(_177_),
    .B2(_386_),
    .X(_018_)
  );
  sky130_fd_sc_hd_o22a_4 _767_ (
    .A1(pll_trim[17]),
    .A2(_384_),
    .B1(_141_),
    .B2(_386_),
    .X(_019_)
  );
  sky130_fd_sc_hd_o22a_4 _768_ (
    .A1(pll_trim[18]),
    .A2(_384_),
    .B1(_144_),
    .B2(_386_),
    .X(_020_)
  );
  sky130_fd_sc_hd_o22a_4 _769_ (
    .A1(pll_trim[19]),
    .A2(_384_),
    .B1(_146_),
    .B2(_386_),
    .X(_021_)
  );
  sky130_fd_sc_hd_o22a_4 _770_ (
    .A1(pll_trim[20]),
    .A2(_384_),
    .B1(_147_),
    .B2(_386_),
    .X(_023_)
  );
  sky130_fd_sc_hd_o22a_4 _771_ (
    .A1(pll_trim[21]),
    .A2(_382_),
    .B1(_148_),
    .B2(_262_),
    .X(_024_)
  );
  sky130_fd_sc_hd_o22a_4 _772_ (
    .A1(pll_trim[22]),
    .A2(_382_),
    .B1(_149_),
    .B2(_262_),
    .X(_025_)
  );
  sky130_fd_sc_hd_o22a_4 _773_ (
    .A1(pll_trim[23]),
    .A2(_382_),
    .B1(_150_),
    .B2(_262_),
    .X(_026_)
  );
  sky130_fd_sc_hd_and2_4 _774_ (
    .A(\U1.wrstb ),
    .B(_224_),
    .X(_396_)
  );
  sky130_fd_sc_hd_buf_4 _775_ (
    .A(_396_),
    .X(_398_)
  );
  sky130_fd_sc_hd_buf_4 _776_ (
    .A(_239_),
    .X(_400_)
  );
  sky130_fd_sc_hd_o22a_4 _777_ (
    .A1(pll_trim[8]),
    .A2(_398_),
    .B1(_177_),
    .B2(_400_),
    .X(_035_)
  );
  sky130_fd_sc_hd_o22a_4 _778_ (
    .A1(pll_trim[9]),
    .A2(_398_),
    .B1(_141_),
    .B2(_400_),
    .X(_036_)
  );
  sky130_fd_sc_hd_o22a_4 _779_ (
    .A1(pll_trim[10]),
    .A2(_398_),
    .B1(_143_),
    .B2(_400_),
    .X(_012_)
  );
  sky130_fd_sc_hd_o22a_4 _780_ (
    .A1(pll_trim[11]),
    .A2(_398_),
    .B1(_146_),
    .B2(_400_),
    .X(_013_)
  );
  sky130_fd_sc_hd_o22a_4 _781_ (
    .A1(pll_trim[12]),
    .A2(_398_),
    .B1(_147_),
    .B2(_400_),
    .X(_014_)
  );
  sky130_fd_sc_hd_o22a_4 _782_ (
    .A1(pll_trim[13]),
    .A2(_396_),
    .B1(_148_),
    .B2(_239_),
    .X(_015_)
  );
  sky130_fd_sc_hd_o22a_4 _783_ (
    .A1(pll_trim[14]),
    .A2(_396_),
    .B1(_149_),
    .B2(_239_),
    .X(_016_)
  );
  sky130_fd_sc_hd_o22a_4 _784_ (
    .A1(pll_trim[15]),
    .A2(_396_),
    .B1(_150_),
    .B2(_239_),
    .X(_017_)
  );
  sky130_fd_sc_hd_inv_4 _785_ (
    .A(RSTB),
    .Y(RST)
  );
  sky130_fd_sc_hd_or2_4 _786_ (
    .A(_109_),
    .B(\U1.writemode ),
    .X(_404_)
  );
  sky130_fd_sc_hd_and3_4 _787_ (
    .A(\U1.state[1] ),
    .B(_100_),
    .C(_404_),
    .X(_073_)
  );
  sky130_fd_sc_hd_buf_4 _788_ (
    .A(_075_),
    .X(_354_)
  );
  sky130_fd_sc_hd_buf_4 _789_ (
    .A(_075_),
    .X(_356_)
  );
  sky130_fd_sc_hd_buf_4 _790_ (
    .A(_075_),
    .X(_358_)
  );
  sky130_fd_sc_hd_buf_4 _791_ (
    .A(_075_),
    .X(_359_)
  );
  sky130_fd_sc_hd_buf_4 _792_ (
    .A(_085_),
    .X(_405_)
  );
  sky130_fd_sc_hd_buf_4 _793_ (
    .A(_405_),
    .X(_361_)
  );
  sky130_fd_sc_hd_buf_4 _794_ (
    .A(_405_),
    .X(_362_)
  );
  sky130_fd_sc_hd_buf_4 _795_ (
    .A(_405_),
    .X(_364_)
  );
  sky130_fd_sc_hd_buf_4 _796_ (
    .A(_405_),
    .X(_365_)
  );
  sky130_fd_sc_hd_buf_4 _797_ (
    .A(_405_),
    .X(_367_)
  );
  sky130_fd_sc_hd_buf_4 _798_ (
    .A(_085_),
    .X(_406_)
  );
  sky130_fd_sc_hd_buf_4 _799_ (
    .A(_406_),
    .X(_368_)
  );
  sky130_fd_sc_hd_buf_4 _800_ (
    .A(_406_),
    .X(_370_)
  );
  sky130_fd_sc_hd_buf_4 _801_ (
    .A(_406_),
    .X(_371_)
  );
  sky130_fd_sc_hd_buf_4 _802_ (
    .A(_406_),
    .X(_373_)
  );
  sky130_fd_sc_hd_buf_4 _803_ (
    .A(_406_),
    .X(_374_)
  );
  sky130_fd_sc_hd_buf_4 _804_ (
    .A(_085_),
    .X(_407_)
  );
  sky130_fd_sc_hd_buf_4 _805_ (
    .A(_407_),
    .X(_376_)
  );
  sky130_fd_sc_hd_buf_4 _806_ (
    .A(_407_),
    .X(_377_)
  );
  sky130_fd_sc_hd_buf_4 _807_ (
    .A(_407_),
    .X(_379_)
  );
  sky130_fd_sc_hd_buf_4 _808_ (
    .A(_407_),
    .X(_380_)
  );
  sky130_fd_sc_hd_buf_4 _809_ (
    .A(_407_),
    .X(_381_)
  );
  sky130_fd_sc_hd_buf_4 _810_ (
    .A(_084_),
    .X(_408_)
  );
  sky130_fd_sc_hd_buf_4 _811_ (
    .A(_408_),
    .X(_383_)
  );
  sky130_fd_sc_hd_buf_4 _812_ (
    .A(_408_),
    .X(_385_)
  );
  sky130_fd_sc_hd_buf_4 _813_ (
    .A(_408_),
    .X(_387_)
  );
  sky130_fd_sc_hd_buf_4 _814_ (
    .A(_408_),
    .X(_388_)
  );
  sky130_fd_sc_hd_buf_4 _815_ (
    .A(_408_),
    .X(_389_)
  );
  sky130_fd_sc_hd_buf_4 _816_ (
    .A(_084_),
    .X(_409_)
  );
  sky130_fd_sc_hd_buf_4 _817_ (
    .A(_409_),
    .X(_390_)
  );
  sky130_fd_sc_hd_buf_4 _818_ (
    .A(_409_),
    .X(_391_)
  );
  sky130_fd_sc_hd_buf_4 _819_ (
    .A(_409_),
    .X(_392_)
  );
  sky130_fd_sc_hd_buf_4 _820_ (
    .A(_409_),
    .X(_393_)
  );
  sky130_fd_sc_hd_buf_4 _821_ (
    .A(_409_),
    .X(_394_)
  );
  sky130_fd_sc_hd_buf_4 _822_ (
    .A(_084_),
    .X(_410_)
  );
  sky130_fd_sc_hd_buf_4 _823_ (
    .A(_410_),
    .X(_395_)
  );
  sky130_fd_sc_hd_buf_4 _824_ (
    .A(_410_),
    .X(_397_)
  );
  sky130_fd_sc_hd_buf_4 _825_ (
    .A(_410_),
    .X(_399_)
  );
  sky130_fd_sc_hd_buf_4 _826_ (
    .A(_410_),
    .X(_401_)
  );
  sky130_fd_sc_hd_buf_4 _827_ (
    .A(_410_),
    .X(_402_)
  );
  sky130_fd_sc_hd_buf_4 _828_ (
    .A(_085_),
    .X(_403_)
  );
  sky130_fd_sc_hd_conb_1 _829_ (
    .HI(mfgr_id[1]),
    .LO()
  );
  sky130_fd_sc_hd_conb_1 _830_ (
    .HI(mfgr_id[2]),
    .LO()
  );
  sky130_fd_sc_hd_conb_1 _831_ (
    .HI(mfgr_id[4]),
    .LO()
  );
  sky130_fd_sc_hd_conb_1 _832_ (
    .HI(mfgr_id[6]),
    .LO()
  );
  sky130_fd_sc_hd_conb_1 _833_ (
    .HI(mfgr_id[10]),
    .LO()
  );
  sky130_fd_sc_hd_conb_1 _834_ (
    .HI(prod_id[0]),
    .LO()
  );
  sky130_fd_sc_hd_conb_1 _835_ (
    .HI(prod_id[2]),
    .LO()
  );
  sky130_fd_sc_hd_conb_1 _836_ (
    .HI(),
    .LO(mfgr_id[0])
  );
  sky130_fd_sc_hd_conb_1 _837_ (
    .HI(),
    .LO(mfgr_id[3])
  );
  sky130_fd_sc_hd_conb_1 _838_ (
    .HI(),
    .LO(mfgr_id[5])
  );
  sky130_fd_sc_hd_conb_1 _839_ (
    .HI(),
    .LO(mfgr_id[7])
  );
  sky130_fd_sc_hd_conb_1 _840_ (
    .HI(),
    .LO(mfgr_id[8])
  );
  sky130_fd_sc_hd_conb_1 _841_ (
    .HI(),
    .LO(mfgr_id[9])
  );
  sky130_fd_sc_hd_conb_1 _842_ (
    .HI(),
    .LO(mfgr_id[11])
  );
  sky130_fd_sc_hd_conb_1 _843_ (
    .HI(),
    .LO(prod_id[1])
  );
  sky130_fd_sc_hd_conb_1 _844_ (
    .HI(),
    .LO(prod_id[3])
  );
  sky130_fd_sc_hd_conb_1 _845_ (
    .HI(),
    .LO(prod_id[4])
  );
  sky130_fd_sc_hd_conb_1 _846_ (
    .HI(),
    .LO(prod_id[5])
  );
  sky130_fd_sc_hd_conb_1 _847_ (
    .HI(),
    .LO(prod_id[6])
  );
  sky130_fd_sc_hd_conb_1 _848_ (
    .HI(),
    .LO(prod_id[7])
  );
  sky130_fd_sc_hd_buf_2 _849_ (
    .A(mask_rev_in[0]),
    .X(mask_rev[0])
  );
  sky130_fd_sc_hd_buf_2 _850_ (
    .A(mask_rev_in[1]),
    .X(mask_rev[1])
  );
  sky130_fd_sc_hd_buf_2 _851_ (
    .A(mask_rev_in[2]),
    .X(mask_rev[2])
  );
  sky130_fd_sc_hd_buf_2 _852_ (
    .A(mask_rev_in[3]),
    .X(mask_rev[3])
  );
  sky130_fd_sc_hd_dfstp_4 _853_ (
    .CLK(clk_0_0),
    .D(_039_),
    .Q(xtal_ena),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _854_ (
    .CLK(clk_0_0),
    .D(_037_),
    .Q(reg_ena),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _855_ (
    .CLK(clk_0_0),
    .D(_002_),
    .Q(pll_dco_ena),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _856_ (
    .CLK(clk_0_0),
    .D(_011_),
    .Q(pll_trim[0]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _857_ (
    .CLK(clk_0_0),
    .D(_022_),
    .Q(pll_trim[1]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _858_ (
    .CLK(clk_0_0),
    .D(_029_),
    .Q(pll_trim[2]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _859_ (
    .CLK(clk_0_0),
    .D(_030_),
    .Q(pll_trim[3]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _860_ (
    .CLK(clk_0_0),
    .D(_031_),
    .Q(pll_trim[4]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _861_ (
    .CLK(clk_0_0),
    .D(_032_),
    .Q(pll_trim[5]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _862_ (
    .CLK(clk_0_0),
    .D(_033_),
    .Q(pll_trim[6]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _863_ (
    .CLK(clk_0_0),
    .D(_034_),
    .Q(pll_trim[7]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _864_ (
    .CLK(clk_0_0),
    .D(_035_),
    .Q(pll_trim[8]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _865_ (
    .CLK(clk_0_0),
    .D(_036_),
    .Q(pll_trim[9]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _866_ (
    .CLK(clk_0_0),
    .D(_012_),
    .Q(pll_trim[10]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _867_ (
    .CLK(clk_0_0),
    .D(_013_),
    .Q(pll_trim[11]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _868_ (
    .CLK(clk_0_0),
    .D(_014_),
    .Q(pll_trim[12]),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _869_ (
    .CLK(clk_0_16),
    .D(_015_),
    .Q(pll_trim[13]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _870_ (
    .CLK(clk_0_16),
    .D(_016_),
    .Q(pll_trim[14]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _871_ (
    .CLK(clk_0_16),
    .D(_017_),
    .Q(pll_trim[15]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _872_ (
    .CLK(clk_0_16),
    .D(_018_),
    .Q(pll_trim[16]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _873_ (
    .CLK(clk_0_16),
    .D(_019_),
    .Q(pll_trim[17]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _874_ (
    .CLK(clk_0_16),
    .D(_020_),
    .Q(pll_trim[18]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _875_ (
    .CLK(clk_0_16),
    .D(_021_),
    .Q(pll_trim[19]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _876_ (
    .CLK(clk_0_16),
    .D(_023_),
    .Q(pll_trim[20]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _877_ (
    .CLK(clk_0_16),
    .D(_024_),
    .Q(pll_trim[21]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _878_ (
    .CLK(clk_0_16),
    .D(_025_),
    .Q(pll_trim[22]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _879_ (
    .CLK(clk_0_16),
    .D(_026_),
    .Q(pll_trim[23]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _880_ (
    .CLK(clk_0_16),
    .D(_027_),
    .Q(pll_trim[24]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _881_ (
    .CLK(clk_0_16),
    .D(_028_),
    .Q(pll_trim[25]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _882_ (
    .CLK(clk_0_16),
    .D(_008_),
    .Q(pll_sel[0]),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _883_ (
    .CLK(clk_0_16),
    .D(_009_),
    .Q(pll_sel[1]),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _884_ (
    .CLK(clk_0_16),
    .D(_010_),
    .Q(pll_sel[2]),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _885_ (
    .CLK(clk_0_32),
    .D(_003_),
    .Q(pll_div[0]),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _886_ (
    .CLK(clk_0_32),
    .D(_004_),
    .Q(pll_div[1]),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _887_ (
    .CLK(clk_0_32),
    .D(_005_),
    .Q(pll_div[2]),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _888_ (
    .CLK(clk_0_32),
    .D(_006_),
    .Q(pll_div[3]),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _889_ (
    .CLK(clk_0_32),
    .D(_007_),
    .Q(pll_div[4]),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfstp_4 _890_ (
    .CLK(clk_0_32),
    .D(_001_),
    .Q(pll_bypass),
    .SETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _891_ (
    .CLK(clk_0_32),
    .D(_000_),
    .Q(irq),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _892_ (
    .CLK(clk_0_32),
    .D(_038_),
    .Q(reset),
    .RESETB(RSTB)
  );
  sky130_fd_sc_hd_dfrtp_4 _893_ (
    .CLK(_082_),
    .D(_073_),
    .Q(\U1.wrstb ),
    .RESETB(_354_)
  );
  sky130_fd_sc_hd_dfrtp_4 _894_ (
    .CLK(_081_),
    .D(_041_),
    .Q(\U1.ldata[0] ),
    .RESETB(_356_)
  );
  sky130_fd_sc_hd_dfrtp_4 _895_ (
    .CLK(_080_),
    .D(_042_),
    .Q(\U1.ldata[1] ),
    .RESETB(_358_)
  );
  sky130_fd_sc_hd_dfrtp_4 _896_ (
    .CLK(_079_),
    .D(_043_),
    .Q(\U1.ldata[2] ),
    .RESETB(_359_)
  );
  sky130_fd_sc_hd_dfrtp_4 _897_ (
    .CLK(_078_),
    .D(_044_),
    .Q(\U1.ldata[3] ),
    .RESETB(_361_)
  );
  sky130_fd_sc_hd_dfrtp_4 _898_ (
    .CLK(_077_),
    .D(_045_),
    .Q(\U1.ldata[4] ),
    .RESETB(_362_)
  );
  sky130_fd_sc_hd_dfrtp_4 _899_ (
    .CLK(_076_),
    .D(_046_),
    .Q(\U1.ldata[5] ),
    .RESETB(_364_)
  );
  sky130_fd_sc_hd_dfrtp_4 _900_ (
    .CLK(_413_),
    .D(_047_),
    .Q(\U1.ldata[6] ),
    .RESETB(_365_)
  );
  sky130_fd_sc_hd_dfrtp_4 _901_ (
    .CLK(_412_),
    .D(_048_),
    .Q(SDO),
    .RESETB(_367_)
  );
  sky130_fd_sc_hd_dfrtp_4 _902_ (
    .CLK(_411_),
    .D(_322_),
    .Q(_083_),
    .RESETB(_368_)
  );
  sky130_fd_sc_hd_dfrtp_4 _903_ (
    .CLK(clk_0_32),
    .D(_066_),
    .Q(\U1.odata[1] ),
    .RESETB(_370_)
  );
  sky130_fd_sc_hd_dfrtp_4 _904_ (
    .CLK(clk_0_32),
    .D(_067_),
    .Q(\U1.odata[2] ),
    .RESETB(_371_)
  );
  sky130_fd_sc_hd_dfrtp_4 _905_ (
    .CLK(clk_0_32),
    .D(_068_),
    .Q(\U1.odata[3] ),
    .RESETB(_373_)
  );
  sky130_fd_sc_hd_dfrtp_4 _906_ (
    .CLK(clk_0_32),
    .D(_069_),
    .Q(\U1.odata[4] ),
    .RESETB(_374_)
  );
  sky130_fd_sc_hd_dfrtp_4 _907_ (
    .CLK(clk_0_32),
    .D(_070_),
    .Q(\U1.odata[5] ),
    .RESETB(_376_)
  );
  sky130_fd_sc_hd_dfrtp_4 _908_ (
    .CLK(clk_0_32),
    .D(_071_),
    .Q(\U1.odata[6] ),
    .RESETB(_377_)
  );
  sky130_fd_sc_hd_dfrtp_4 _909_ (
    .CLK(clk_0_32),
    .D(_072_),
    .Q(\U1.odata[7] ),
    .RESETB(_379_)
  );
  sky130_fd_sc_hd_dfrtp_4 _910_ (
    .CLK(clk_0_32),
    .D(_063_),
    .Q(\U1.fixed[0] ),
    .RESETB(_380_)
  );
  sky130_fd_sc_hd_dfrtp_4 _911_ (
    .CLK(clk_0_48),
    .D(_064_),
    .Q(\U1.fixed[1] ),
    .RESETB(_381_)
  );
  sky130_fd_sc_hd_dfrtp_4 _912_ (
    .CLK(clk_0_48),
    .D(_065_),
    .Q(\U1.fixed[2] ),
    .RESETB(_383_)
  );
  sky130_fd_sc_hd_dfrtp_4 _913_ (
    .CLK(clk_0_48),
    .D(_062_),
    .Q(\U1.readmode ),
    .RESETB(_385_)
  );
  sky130_fd_sc_hd_dfrtp_4 _914_ (
    .CLK(clk_0_48),
    .D(_061_),
    .Q(\U1.writemode ),
    .RESETB(_387_)
  );
  sky130_fd_sc_hd_dfrtp_4 _915_ (
    .CLK(clk_0_48),
    .D(_057_),
    .Q(\U1.count[0] ),
    .RESETB(_388_)
  );
  sky130_fd_sc_hd_dfrtp_4 _916_ (
    .CLK(clk_0_48),
    .D(_059_),
    .Q(\U1.count[1] ),
    .RESETB(_389_)
  );
  sky130_fd_sc_hd_dfrtp_4 _917_ (
    .CLK(clk_0_48),
    .D(_060_),
    .Q(\U1.count[2] ),
    .RESETB(_390_)
  );
  sky130_fd_sc_hd_dfrtp_4 _918_ (
    .CLK(clk_0_48),
    .D(_049_),
    .Q(\U1.addr[0] ),
    .RESETB(_391_)
  );
  sky130_fd_sc_hd_dfrtp_4 _919_ (
    .CLK(clk_0_48),
    .D(_050_),
    .Q(\U1.addr[1] ),
    .RESETB(_392_)
  );
  sky130_fd_sc_hd_dfrtp_4 _920_ (
    .CLK(clk_0_48),
    .D(_051_),
    .Q(\U1.addr[2] ),
    .RESETB(_393_)
  );
  sky130_fd_sc_hd_dfrtp_4 _921_ (
    .CLK(clk_0_48),
    .D(_052_),
    .Q(\U1.addr[3] ),
    .RESETB(_394_)
  );
  sky130_fd_sc_hd_dfrtp_4 _922_ (
    .CLK(clk_0_48),
    .D(_053_),
    .Q(\U1.addr[4] ),
    .RESETB(_395_)
  );
  sky130_fd_sc_hd_dfrtp_4 _923_ (
    .CLK(clk_0_48),
    .D(_054_),
    .Q(\U1.addr[5] ),
    .RESETB(_397_)
  );
  sky130_fd_sc_hd_dfrtp_4 _924_ (
    .CLK(clk_0_48),
    .D(_055_),
    .Q(\U1.addr[6] ),
    .RESETB(_399_)
  );
  sky130_fd_sc_hd_dfrtp_4 _925_ (
    .CLK(clk_0_48),
    .D(_056_),
    .Q(\U1.addr[7] ),
    .RESETB(_401_)
  );
  sky130_fd_sc_hd_dfstp_4 _926_ (
    .CLK(clk_0_48),
    .D(_058_),
    .Q(\U1.state[0] ),
    .SETB(_402_)
  );
  sky130_fd_sc_hd_dfrtp_4 _927_ (
    .CLK(clk_0_64),
    .D(_074_),
    .Q(\U1.state[1] ),
    .RESETB(_403_)
  );
  sky130_fd_sc_hd_dfrtp_4 _928_ (
    .CLK(clk_0_64),
    .D(_040_),
    .Q(\U1.state[2] ),
    .RESETB(_075_)
  );
endmodule
